/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransaction {
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "txId")]
    pub tx_id: String,
    /// Natural number representing block height
    
    #[serde(rename = "blockHeight")]
    pub block_height: i32,
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "blockHash")]
    pub block_hash: String,
    /// Transaction timestamp
    
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    /// Transaction type from address perspective
    
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Amount transferred (in nicks)
    
    #[serde(rename = "amount")]
    pub amount: i64,
    /// Transaction fee (in nicks)
    
    #[serde(rename = "fee")]
    pub fee: i64,
    /// Transaction inputs
    
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<models::TransactionInput>>,
    /// Transaction outputs
    
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::TransactionOutput>>,
    /// Optional transaction note/memo
    
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// All counterparty addresses in this transaction
    
    #[serde(rename = "counterparties", skip_serializing_if = "Option::is_none")]
    pub counterparties: Option<Vec<String>>,
}

impl AddressTransaction {
    pub fn new(tx_id: String, block_height: i32, block_hash: String, timestamp: i32, r#type: Type, amount: i64, fee: i64) -> AddressTransaction {
        AddressTransaction {
            tx_id,
            block_height,
            block_hash,
            timestamp,
            r#type,
            amount,
            fee,
            inputs: None,
            outputs: None,
            note: None,
            counterparties: None,
        }
    }
}
/// Transaction type from address perspective
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "received")]
    Received,
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "self")]
    VariantSelf,
}

impl Default for Type {
    fn default() -> Type {
        Self::Received
    }
}

