/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransactionsResponseFeeMetricsLastBlock {
    
    #[serde(rename = "totalFees", skip_serializing_if = "Option::is_none")]
    pub total_fees: Option<i64>,
    
    #[serde(rename = "avgFeeRate", skip_serializing_if = "Option::is_none")]
    pub avg_fee_rate: Option<f64>,
    
    #[serde(rename = "txCount", skip_serializing_if = "Option::is_none")]
    pub tx_count: Option<i32>,
}

impl AddressTransactionsResponseFeeMetricsLastBlock {
    pub fn new() -> AddressTransactionsResponseFeeMetricsLastBlock {
        AddressTransactionsResponseFeeMetricsLastBlock {
            total_fees: None,
            avg_fee_rate: None,
            tx_count: None,
        }
    }
}

