/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressesWithBalanceResponse {
    
    #[serde(rename = "items")]
    pub items: Vec<models::AddressBalanceItem>,
    
    #[serde(rename = "totalCount")]
    pub total_count: i32,
    
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::PaginationInfo>>,
}

impl AddressesWithBalanceResponse {
    pub fn new(items: Vec<models::AddressBalanceItem>, total_count: i32) -> AddressesWithBalanceResponse {
        AddressesWithBalanceResponse {
            items,
            total_count,
            pagination: None,
        }
    }
}

