/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransactionsResponseFeeMetricsRecommended {
    /// Fee rate for confirmation in ~1 hour
    
    #[serde(rename = "slow", skip_serializing_if = "Option::is_none")]
    pub slow: Option<f64>,
    /// Fee rate for confirmation in ~30 min
    
    #[serde(rename = "medium", skip_serializing_if = "Option::is_none")]
    pub medium: Option<f64>,
    /// Fee rate for confirmation in ~10 min
    
    #[serde(rename = "fast", skip_serializing_if = "Option::is_none")]
    pub fast: Option<f64>,
}

impl AddressTransactionsResponseFeeMetricsRecommended {
    pub fn new() -> AddressTransactionsResponseFeeMetricsRecommended {
        AddressTransactionsResponseFeeMetricsRecommended {
            slow: None,
            medium: None,
            fast: None,
        }
    }
}

