/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressBalanceItem {
    /// Base58-encoded Schnorr public key address (132 characters)
    
    #[serde(rename = "address")]
    pub address: String,
    
    #[serde(rename = "balance")]
    pub balance: i64,
    /// Number of notes contributing to this balance
    
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<i64>,
}

impl AddressBalanceItem {
    pub fn new(address: String, balance: i64) -> AddressBalanceItem {
        AddressBalanceItem {
            address,
            balance,
            notes: None,
        }
    }
}

