/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransactionsResponseMempool {
    /// Number of unconfirmed transactions
    
    #[serde(rename = "count")]
    pub count: i32,
    /// Total fees in mempool
    
    #[serde(rename = "totalFees")]
    pub total_fees: i64,
    /// Average fee rate (fees per byte)
    
    #[serde(rename = "avgFeeRate")]
    pub avg_fee_rate: f64,
}

impl AddressTransactionsResponseMempool {
    pub fn new(count: i32, total_fees: i64, avg_fee_rate: f64) -> AddressTransactionsResponseMempool {
        AddressTransactionsResponseMempool {
            count,
            total_fees,
            avg_fee_rate,
        }
    }
}

