/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransactionsResponseFeeMetrics {
    
    #[serde(rename = "lastBlock")]
    pub last_block: Box<models::AddressTransactionsResponseFeeMetricsLastBlock>,
    
    #[serde(rename = "recommended")]
    pub recommended: Box<models::AddressTransactionsResponseFeeMetricsRecommended>,
}

impl AddressTransactionsResponseFeeMetrics {
    pub fn new(last_block: models::AddressTransactionsResponseFeeMetricsLastBlock, recommended: models::AddressTransactionsResponseFeeMetricsRecommended) -> AddressTransactionsResponseFeeMetrics {
        AddressTransactionsResponseFeeMetrics {
            last_block: Box::new(last_block),
            recommended: Box::new(recommended),
        }
    }
}

