/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransactionsParam {
    /// Base58-encoded Schnorr public key address (132 characters)
    
    #[serde(rename = "address")]
    pub address: String,
    /// Maximum number of transactions to return
    
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Number of transactions to skip (for pagination)
    
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Only include transactions from this block height onwards
    
    #[serde(rename = "minHeight", skip_serializing_if = "Option::is_none")]
    pub min_height: Option<i32>,
    /// Only include transactions up to this block height
    
    #[serde(rename = "maxHeight", skip_serializing_if = "Option::is_none")]
    pub max_height: Option<i32>,
}

impl AddressTransactionsParam {
    pub fn new(address: String) -> AddressTransactionsParam {
        AddressTransactionsParam {
            address,
            limit: None,
            offset: None,
            min_height: None,
            max_height: None,
        }
    }
}

