/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransactionsResponseNetworkProofrate {
    /// Current network proof rate (proofs/second)
    
    #[serde(rename = "current")]
    pub current: f64,
    /// 24h average proof rate
    
    #[serde(rename = "avg24h")]
    pub avg24h: f64,
    /// 7 day average proof rate
    
    #[serde(rename = "avg7d")]
    pub avg7d: f64,
}

impl AddressTransactionsResponseNetworkProofrate {
    pub fn new(current: f64, avg24h: f64, avg7d: f64) -> AddressTransactionsResponseNetworkProofrate {
        AddressTransactionsResponseNetworkProofrate {
            current,
            avg24h,
            avg7d,
        }
    }
}

