/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressTransactionsResponse {
    /// Base58-encoded Schnorr public key address (132 characters)
    
    #[serde(rename = "address")]
    pub address: String,
    /// Total number of transactions for this address
    
    #[serde(rename = "totalTransactions")]
    pub total_transactions: i32,
    /// Total amount received by this address (in nicks)
    
    #[serde(rename = "totalReceived", skip_serializing_if = "Option::is_none")]
    pub total_received: Option<i64>,
    /// Total amount sent from this address (in nicks)
    
    #[serde(rename = "totalSent", skip_serializing_if = "Option::is_none")]
    pub total_sent: Option<i64>,
    /// Current balance (totalReceived - totalSent)
    
    #[serde(rename = "currentBalance", skip_serializing_if = "Option::is_none")]
    pub current_balance: Option<i64>,
    /// Array of transactions involving this address
    
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::AddressTransaction>,
    
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::PaginationInfo>>,
    
    #[serde(rename = "networkProofrate", skip_serializing_if = "Option::is_none")]
    pub network_proofrate: Option<Box<models::AddressTransactionsResponseNetworkProofrate>>,
    
    #[serde(rename = "mempool", skip_serializing_if = "Option::is_none")]
    pub mempool: Option<Box<models::AddressTransactionsResponseMempool>>,
    
    #[serde(rename = "feeMetrics", skip_serializing_if = "Option::is_none")]
    pub fee_metrics: Option<Box<models::AddressTransactionsResponseFeeMetrics>>,
}

impl AddressTransactionsResponse {
    pub fn new(address: String, total_transactions: i32, transactions: Vec<models::AddressTransaction>) -> AddressTransactionsResponse {
        AddressTransactionsResponse {
            address,
            total_transactions,
            total_received: None,
            total_sent: None,
            current_balance: None,
            transactions,
            pagination: None,
            network_proofrate: None,
            mempool: None,
            fee_metrics: None,
        }
    }
}

