/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceObject {
    
    #[serde(rename = "nicks", skip_serializing_if = "Option::is_none")]
    pub nicks: Option<i64>,
    
    #[serde(rename = "notes")]
    pub notes: Vec<models::NoteObject>,
}

impl BalanceObject {
    pub fn new(notes: Vec<models::NoteObject>) -> BalanceObject {
        BalanceObject {
            nicks: None,
            notes,
        }
    }
}

