/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksRangeResponseEpochInfo {
    /// Current difficulty epoch (height / 2016)
    
    #[serde(rename = "currentEpoch")]
    pub current_epoch: i32,
    /// Blocks processed in current epoch
    
    #[serde(rename = "blocksInEpoch")]
    pub blocks_in_epoch: i32,
    /// Average block time for current 2016 block epoch
    
    #[serde(rename = "avgBlockTimeThisEpoch")]
    pub avg_block_time_this_epoch: f64,
}

impl BlocksRangeResponseEpochInfo {
    pub fn new(current_epoch: i32, blocks_in_epoch: i32, avg_block_time_this_epoch: f64) -> BlocksRangeResponseEpochInfo {
        BlocksRangeResponseEpochInfo {
            current_epoch,
            blocks_in_epoch,
            avg_block_time_this_epoch,
        }
    }
}

