/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockObject {
    /// Block hash as base58 string
    
    #[serde(rename = "hash")]
    pub hash: String,
    /// Block height in the chain
    
    #[serde(rename = "height")]
    pub height: i32,
    /// Block timestamp as seconds since Unix epoch UTC
    
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    /// List of transaction IDs included in this block
    
    #[serde(rename = "transactions")]
    pub transactions: Vec<String>,
    /// Human-readable difficulty expression
    
    #[serde(rename = "difficulty")]
    pub difficulty: String,
    /// Difficulty as a floating-point exponent
    
    #[serde(rename = "difficultyExp")]
    pub difficulty_exp: f64,
    /// Effective proof rate observed for this block
    
    #[serde(rename = "proofsPerSecond")]
    pub proofs_per_second: f64,
    /// Parent block hash as base58
    
    #[serde(rename = "parent")]
    pub parent: String,
    /// Bigint mining target for this block as a string
    
    #[serde(rename = "target")]
    pub target: String,
    /// List of coinbase recipients and their awarded amounts
    
    #[serde(rename = "coinbase")]
    pub coinbase: Vec<models::CoinbaseRecipient>,
    /// Counter within the current mining epoch
    
    #[serde(rename = "epochCounter", skip_serializing_if = "Option::is_none")]
    pub epoch_counter: Option<i64>,
    /// Total accumulated proof-of-work up to this block
    
    #[serde(rename = "accumulatedWork", skip_serializing_if = "Option::is_none")]
    pub accumulated_work: Option<i64>,
    /// Optional message included in the block
    
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
    /// Number of transactions in this block
    
    #[serde(rename = "transactionCount", skip_serializing_if = "Option::is_none")]
    pub transaction_count: Option<i32>,
    /// Total size of the block in bytes
    
    #[serde(rename = "blockSize", skip_serializing_if = "Option::is_none")]
    pub block_size: Option<i32>,
    /// Total transaction fees in this block
    
    #[serde(rename = "totalFees", skip_serializing_if = "Option::is_none")]
    pub total_fees: Option<i64>,
}

impl BlockObject {
    pub fn new(hash: String, height: i32, timestamp: i32, transactions: Vec<String>, difficulty: String, difficulty_exp: f64, proofs_per_second: f64, parent: String, target: String, coinbase: Vec<models::CoinbaseRecipient>) -> BlockObject {
        BlockObject {
            hash,
            height,
            timestamp,
            transactions,
            difficulty,
            difficulty_exp,
            proofs_per_second,
            parent,
            target,
            coinbase,
            epoch_counter: None,
            accumulated_work: None,
            msg: None,
            transaction_count: None,
            block_size: None,
            total_fees: None,
        }
    }
}

