/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlocksRangeResponseMetadata : Optional metadata about the query
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksRangeResponseMetadata {
    /// Whether results were served from cache
    
    #[serde(rename = "cached", skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
    /// Query execution time in milliseconds
    
    #[serde(rename = "queryTimeMs", skip_serializing_if = "Option::is_none")]
    pub query_time_ms: Option<f64>,
}

impl BlocksRangeResponseMetadata {
    /// Optional metadata about the query
    pub fn new() -> BlocksRangeResponseMetadata {
        BlocksRangeResponseMetadata {
            cached: None,
            query_time_ms: None,
        }
    }
}

