/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksRangeResponseProofRateOverTimeInner {
    
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    
    #[serde(rename = "proofRate", skip_serializing_if = "Option::is_none")]
    pub proof_rate: Option<f64>,
    
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i32>,
}

impl BlocksRangeResponseProofRateOverTimeInner {
    pub fn new() -> BlocksRangeResponseProofRateOverTimeInner {
        BlocksRangeResponseProofRateOverTimeInner {
            height: None,
            proof_rate: None,
            timestamp: None,
        }
    }
}

