/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksRangeResponse {
    /// Total number of blocks returned
    
    #[serde(rename = "totalBlocks")]
    pub total_blocks: i32,
    /// Starting block height (inclusive)
    
    #[serde(rename = "startHeight")]
    pub start_height: i32,
    /// Ending block height (inclusive)
    
    #[serde(rename = "endHeight")]
    pub end_height: i32,
    /// Earliest timestamp in the range
    
    #[serde(rename = "minTimestamp", skip_serializing_if = "Option::is_none")]
    pub min_timestamp: Option<i32>,
    /// Latest timestamp in the range
    
    #[serde(rename = "maxTimestamp", skip_serializing_if = "Option::is_none")]
    pub max_timestamp: Option<i32>,
    /// Array of blocks in the requested range
    
    #[serde(rename = "blocks")]
    pub blocks: Vec<models::BlockObject>,
    
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::BlocksRangeResponseMetadata>>,
    /// Average block time in seconds (last 144 blocks)
    
    #[serde(rename = "avgBlockTime", skip_serializing_if = "Option::is_none")]
    pub avg_block_time: Option<f64>,
    /// Proof rate history over recent blocks
    
    #[serde(rename = "proofRateOverTime", skip_serializing_if = "Option::is_none")]
    pub proof_rate_over_time: Option<Vec<models::BlocksRangeResponseProofRateOverTimeInner>>,
    /// Seconds since last block
    
    #[serde(rename = "timeSinceLastBlock", skip_serializing_if = "Option::is_none")]
    pub time_since_last_block: Option<f64>,
    
    #[serde(rename = "epochInfo", skip_serializing_if = "Option::is_none")]
    pub epoch_info: Option<Box<models::BlocksRangeResponseEpochInfo>>,
    
    #[serde(rename = "difficultyAdjustment", skip_serializing_if = "Option::is_none")]
    pub difficulty_adjustment: Option<Box<models::BlocksRangeResponseDifficultyAdjustment>>,
    
    #[serde(rename = "halvingInfo", skip_serializing_if = "Option::is_none")]
    pub halving_info: Option<Box<models::BlocksRangeResponseHalvingInfo>>,
}

impl BlocksRangeResponse {
    pub fn new(total_blocks: i32, start_height: i32, end_height: i32, blocks: Vec<models::BlockObject>) -> BlocksRangeResponse {
        BlocksRangeResponse {
            total_blocks,
            start_height,
            end_height,
            min_timestamp: None,
            max_timestamp: None,
            blocks,
            metadata: None,
            avg_block_time: None,
            proof_rate_over_time: None,
            time_since_last_block: None,
            epoch_info: None,
            difficulty_adjustment: None,
            halving_info: None,
        }
    }
}

