/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksRangeResponseDifficultyAdjustment {
    /// Blocks remaining until next difficulty adjustment
    
    #[serde(rename = "blocksToAdjustment")]
    pub blocks_to_adjustment: i32,
    /// Estimated seconds until difficulty adjustment
    
    #[serde(rename = "estimatedTimeToAdjustment")]
    pub estimated_time_to_adjustment: f64,
    /// Estimated next difficulty multiplier
    
    #[serde(rename = "estimatedNextDifficulty")]
    pub estimated_next_difficulty: f64,
}

impl BlocksRangeResponseDifficultyAdjustment {
    pub fn new(blocks_to_adjustment: i32, estimated_time_to_adjustment: f64, estimated_next_difficulty: f64) -> BlocksRangeResponseDifficultyAdjustment {
        BlocksRangeResponseDifficultyAdjustment {
            blocks_to_adjustment,
            estimated_time_to_adjustment,
            estimated_next_difficulty,
        }
    }
}

