/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksRangeResponseHalvingInfo {
    /// Blocks remaining until next reward halving
    
    #[serde(rename = "blocksToHalving")]
    pub blocks_to_halving: i32,
    /// Estimated seconds until halving
    
    #[serde(rename = "estimatedTimeToHalving")]
    pub estimated_time_to_halving: f64,
    /// Current block reward in smallest units
    
    #[serde(rename = "currentBlockReward")]
    pub current_block_reward: i64,
}

impl BlocksRangeResponseHalvingInfo {
    pub fn new(blocks_to_halving: i32, estimated_time_to_halving: f64, current_block_reward: i64) -> BlocksRangeResponseHalvingInfo {
        BlocksRangeResponseHalvingInfo {
            blocks_to_halving,
            estimated_time_to_halving,
            current_block_reward,
        }
    }
}

