/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoinbaseRecipient {
    /// Base58-encoded Schnorr public key address (132 characters)
    
    #[serde(rename = "address")]
    pub address: String,
    /// Amount of nicks (cryptocurrency units) awarded to this address
    
    #[serde(rename = "nicks")]
    pub nicks: i64,
}

impl CoinbaseRecipient {
    pub fn new(address: String, nicks: i64) -> CoinbaseRecipient {
        CoinbaseRecipient {
            address,
            nicks,
        }
    }
}

