/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecentralizationMetricsResponseMetadata {
    /// Total number of analysis windows
    
    #[serde(rename = "totalWindows", skip_serializing_if = "Option::is_none")]
    pub total_windows: Option<i32>,
    /// Query execution time in milliseconds
    
    #[serde(rename = "queryTimeMs", skip_serializing_if = "Option::is_none")]
    pub query_time_ms: Option<f64>,
    /// Whether results were served from cache
    
    #[serde(rename = "cached", skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
}

impl DecentralizationMetricsResponseMetadata {
    pub fn new() -> DecentralizationMetricsResponseMetadata {
        DecentralizationMetricsResponseMetadata {
            total_windows: None,
            query_time_ms: None,
            cached: None,
        }
    }
}

