/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecentralizationMetricsResponse {
    /// Starting block height of analysis
    
    #[serde(rename = "startHeight")]
    pub start_height: i32,
    /// Ending block height of analysis
    
    #[serde(rename = "endHeight")]
    pub end_height: i32,
    /// Size of each analysis window
    
    #[serde(rename = "windowSize")]
    pub window_size: i32,
    /// Mining decentralization metrics over time
    
    #[serde(rename = "miningDecentralization")]
    pub mining_decentralization: Vec<models::MiningDecentralizationWindow>,
    /// Wallet growth metrics over time
    
    #[serde(rename = "walletGrowth")]
    pub wallet_growth: Vec<models::WalletGrowthWindow>,
    
    #[serde(rename = "metadata")]
    pub metadata: Box<models::DecentralizationMetricsResponseMetadata>,
}

impl DecentralizationMetricsResponse {
    pub fn new(start_height: i32, end_height: i32, window_size: i32, mining_decentralization: Vec<models::MiningDecentralizationWindow>, wallet_growth: Vec<models::WalletGrowthWindow>, metadata: models::DecentralizationMetricsResponseMetadata) -> DecentralizationMetricsResponse {
        DecentralizationMetricsResponse {
            start_height,
            end_height,
            window_size,
            mining_decentralization,
            wallet_growth,
            metadata: Box::new(metadata),
        }
    }
}

