/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAddressesWithBalanceParamsInner {
    
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Filter addresses with at least this balance (default: 1)
    
    #[serde(rename = "minBalance", skip_serializing_if = "Option::is_none")]
    pub min_balance: Option<i64>,
    /// Optional address prefix filter
    
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
}

impl GetAddressesWithBalanceParamsInner {
    pub fn new() -> GetAddressesWithBalanceParamsInner {
        GetAddressesWithBalanceParamsInner {
            limit: None,
            offset: None,
            min_balance: None,
            prefix: None,
        }
    }
}

