/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBlockByHeightRequestId {
    // variant debug: name=String, baseName=one_of_0, dataType=String, complexType=, title=, ref=
    String
(String),
    // variant debug: name=Integer, baseName=one_of_1, dataType=i32, complexType=, title=, ref=
    Integer
(i32),
}

impl Default for GetBlockByHeightRequestId {
    fn default() -> Self {
        Self::String
(Default::default())
    }
}

