/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionsByBlockIdParamsInner {
    /// Block ID to query transactions for
    
    #[serde(rename = "id")]
    pub id: String,
    /// Maximum number of transactions to return
    
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Number of transactions to skip
    
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
}

impl GetTransactionsByBlockIdParamsInner {
    pub fn new(id: String) -> GetTransactionsByBlockIdParamsInner {
        GetTransactionsByBlockIdParamsInner {
            id,
            limit: None,
            offset: None,
        }
    }
}

