/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProofRateHistoryParamsInner {
    /// Starting block height for the history
    
    #[serde(rename = "startHeight", skip_serializing_if = "Option::is_none")]
    pub start_height: Option<i32>,
    /// Ending block height for the history
    
    #[serde(rename = "endHeight", skip_serializing_if = "Option::is_none")]
    pub end_height: Option<i32>,
    /// Maximum number of data points to return
    
    #[serde(rename = "maxSamples", skip_serializing_if = "Option::is_none")]
    pub max_samples: Option<i32>,
    /// The type of proofrate to return
    
    #[serde(rename = "smoothingType", skip_serializing_if = "Option::is_none")]
    pub smoothing_type: Option<SmoothingType>,
}

impl GetProofRateHistoryParamsInner {
    pub fn new() -> GetProofRateHistoryParamsInner {
        GetProofRateHistoryParamsInner {
            start_height: None,
            end_height: None,
            max_samples: None,
            smoothing_type: None,
        }
    }
}
/// The type of proofrate to return
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SmoothingType {
    #[serde(rename = "raw")]
    Raw,
    #[serde(rename = "smoothed_100")]
    Smoothed100,
    #[serde(rename = "smoothed_50")]
    Smoothed50,
}

impl Default for SmoothingType {
    fn default() -> SmoothingType {
        Self::Raw
    }
}

