/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkHealthSummaryParamsInner {
    /// Block height to analyze (defaults to current tip)
    
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
}

impl GetNetworkHealthSummaryParamsInner {
    pub fn new() -> GetNetworkHealthSummaryParamsInner {
        GetNetworkHealthSummaryParamsInner {
            height: None,
        }
    }
}

