/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockchainMetricsParamsInner {
    /// End block height to analyze (defaults to current tip)
    
    #[serde(rename = "blockHeight", skip_serializing_if = "Option::is_none")]
    pub block_height: Option<i32>,
    /// Start block height for range analysis (defaults to 0)
    
    #[serde(rename = "startHeight", skip_serializing_if = "Option::is_none")]
    pub start_height: Option<i32>,
    /// End block height for range analysis (defaults to current tip)
    
    #[serde(rename = "endHeight", skip_serializing_if = "Option::is_none")]
    pub end_height: Option<i32>,
    /// Size of chunks for proof rate history aggregation (auto-calculated if not provided)
    
    #[serde(rename = "chunkSize", skip_serializing_if = "Option::is_none")]
    pub chunk_size: Option<i32>,
}

impl GetBlockchainMetricsParamsInner {
    pub fn new() -> GetBlockchainMetricsParamsInner {
        GetBlockchainMetricsParamsInner {
            block_height: None,
            start_height: None,
            end_height: None,
            chunk_size: None,
        }
    }
}

