/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockByHeightRequest {
    
    #[serde(rename = "jsonrpc")]
    pub jsonrpc: Jsonrpc,
    
    #[serde(rename = "method")]
    pub method: Method,
    
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<Box<models::GetBlockByHeightRequestId>>,
    
    #[serde(rename = "params")]
    pub params: Vec<models::HeightParam>,
}

impl GetBlockByHeightRequest {
    pub fn new(jsonrpc: Jsonrpc, method: Method, id: Option<models::GetBlockByHeightRequestId>, params: Vec<models::HeightParam>) -> GetBlockByHeightRequest {
        GetBlockByHeightRequest {
            jsonrpc,
            method,
            id: if let Some(x) = id {Some(Box::new(x))} else {None},
            params,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Jsonrpc {
    #[serde(rename = "2.0")]
    Variant2Period0,
}

impl Default for Jsonrpc {
    fn default() -> Jsonrpc {
        Self::Variant2Period0
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "getBlockByHeight")]
    GetBlockByHeight,
}

impl Default for Method {
    fn default() -> Method {
        Self::GetBlockByHeight
    }
}

