/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDecentralizationMetricsParamsInner {
    /// Starting block height for analysis (defaults to 0)
    
    #[serde(rename = "startHeight", skip_serializing_if = "Option::is_none")]
    pub start_height: Option<i32>,
    /// Ending block height for analysis (defaults to current tip)
    
    #[serde(rename = "endHeight", skip_serializing_if = "Option::is_none")]
    pub end_height: Option<i32>,
    /// Size of each analysis window in blocks
    
    #[serde(rename = "windowSize", skip_serializing_if = "Option::is_none")]
    pub window_size: Option<i32>,
    /// Maximum number of data points to return (for time series)
    
    #[serde(rename = "dataPoints", skip_serializing_if = "Option::is_none")]
    pub data_points: Option<i32>,
}

impl GetDecentralizationMetricsParamsInner {
    pub fn new() -> GetDecentralizationMetricsParamsInner {
        GetDecentralizationMetricsParamsInner {
            start_height: None,
            end_height: None,
            window_size: None,
            data_points: None,
        }
    }
}

