/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeavySummaryObject {
    /// List of mining public keys
    
    #[serde(rename = "pubkeys")]
    pub pubkeys: Vec<String>,
    /// Summary of the heaviest block
    
    #[serde(rename = "pageSummary", skip_serializing_if = "Option::is_none")]
    pub page_summary: Option<Box<models::PageSummary>>,
}

impl HeavySummaryObject {
    pub fn new(pubkeys: Vec<String>) -> HeavySummaryObject {
        HeavySummaryObject {
            pubkeys,
            page_summary: None,
        }
    }
}

