/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeightWithPreviousParam {
    
    #[serde(rename = "height")]
    pub height: i32,
    
    #[serde(rename = "previousCount")]
    pub previous_count: i32,
}

impl HeightWithPreviousParam {
    pub fn new(height: i32, previous_count: i32) -> HeightWithPreviousParam {
        HeightWithPreviousParam {
            height,
            previous_count,
        }
    }
}

