/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcRequestEnvelope {
    #[serde(rename="getBlockByHeight")]
    GetBlockByHeight(Box<models::GetBlockByHeightRequest>),
    #[serde(rename="getBlockByHash")]
    GetBlockByHash(Box<models::GetBlockByHashRequest>),
    #[serde(rename="getBlocksByRange")]
    GetBlocksByRange(Box<models::GetBlocksByRangeRequest>),
    #[serde(rename="getBlocksByTimestampRange")]
    GetBlocksByTimestampRange(Box<models::GetBlocksByTimestampRangeRequest>),
    #[serde(rename="getTip")]
    GetTip(Box<models::GetTipRequest>),
    #[serde(rename="getHeight")]
    GetHeight(Box<models::GetHeightRequest>),
    #[serde(rename="getTransactionById")]
    GetTransactionById(Box<models::GetTransactionByIdRequest>),
    #[serde(rename="getAllTransactions")]
    GetAllTransactions(Box<models::GetAllTransactionsRequest>),
    #[serde(rename="getTransactionsByAddress")]
    GetTransactionsByAddress(Box<models::GetTransactionsByAddressRequest>),
    #[serde(rename="getRawTransactionById")]
    GetRawTransactionById(Box<models::GetRawTransactionByIdRequest>),
    #[serde(rename="getBalanceByAddress")]
    GetBalanceByAddress(Box<models::GetBalanceByAddressRequest>),
    #[serde(rename="getMiningPubkeys")]
    GetMiningPubkeys(Box<models::GetMiningPubkeysRequest>),
    #[serde(rename="getHeavySummary")]
    GetHeavySummary(Box<models::GetHeavySummaryRequest>),
    #[serde(rename="isMainnet")]
    IsMainnet(Box<models::IsMainnetRequest>),
    #[serde(rename="submitTransaction")]
    SubmitTransaction(Box<models::SubmitTransactionRequest>),
    #[serde(rename="getBlockchainMetrics")]
    GetBlockchainMetrics(Box<models::GetBlockchainMetricsRequest>),
    #[serde(rename="getTransactionsByBlockId")]
    GetTransactionsByBlockId(Box<models::GetTransactionsByBlockIdRequest>),
    #[serde(rename="getTransactionsByBlockHeight")]
    GetTransactionsByBlockHeight(Box<models::GetTransactionsByBlockHeightRequest>),
    #[serde(rename="getDecentralizationMetrics")]
    GetDecentralizationMetrics(Box<models::GetDecentralizationMetricsRequest>),
    #[serde(rename="getNetworkHealthSummary")]
    GetNetworkHealthSummary(Box<models::GetNetworkHealthSummaryRequest>),
    #[serde(rename="getMiningDecentralization")]
    GetMiningDecentralization(Box<models::GetMiningDecentralizationRequest>),
    #[serde(rename="getWalletGrowthMetrics")]
    GetWalletGrowthMetrics(Box<models::GetWalletGrowthMetricsRequest>),
    #[serde(rename="getNotes")]
    GetNotes(Box<models::GetNotesRequest>),
    #[serde(rename="getProofRateHistory")]
    GetProofRateHistory(Box<models::GetProofRateHistoryRequest>),
    #[serde(rename="getAddressesWithBalance")]
    GetAddressesWithBalance(Box<models::GetAddressesWithBalanceRequest>),
}

impl Default for JsonRpcRequestEnvelope {
    fn default() -> Self {
        Self::GetBlockByHeight(Default::default())
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Jsonrpc {
    #[serde(rename = "2.0")]
    Variant2Period0,
}

impl Default for Jsonrpc {
    fn default() -> Jsonrpc {
        Self::Variant2Period0
    }
}

