/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinerStats {
    /// Base58-encoded Schnorr public key address (132 characters)
    
    #[serde(rename = "address")]
    pub address: String,
    /// Number of blocks mined by this miner
    
    #[serde(rename = "blocksMined")]
    pub blocks_mined: i32,
    /// Total rewards earned in nicks
    
    #[serde(rename = "totalRewards")]
    pub total_rewards: i64,
    /// Percentage of total blocks mined (0-100)
    
    #[serde(rename = "sharePercentage")]
    pub share_percentage: f64,
    /// First block height mined by this miner
    
    #[serde(rename = "firstBlock")]
    pub first_block: i32,
    /// Last block height mined by this miner
    
    #[serde(rename = "lastBlock")]
    pub last_block: i32,
    /// Average difficulty of blocks mined by this miner
    
    #[serde(rename = "avgDifficulty", skip_serializing_if = "Option::is_none")]
    pub avg_difficulty: Option<f64>,
}

impl MinerStats {
    pub fn new(address: String, blocks_mined: i32, total_rewards: i64, share_percentage: f64, first_block: i32, last_block: i32) -> MinerStats {
        MinerStats {
            address,
            blocks_mined,
            total_rewards,
            share_percentage,
            first_block,
            last_block,
            avg_difficulty: None,
        }
    }
}

