/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MiningDecentralizationWindow {
    /// Starting block height of this window
    
    #[serde(rename = "startHeight")]
    pub start_height: i32,
    /// Ending block height of this window
    
    #[serde(rename = "endHeight")]
    pub end_height: i32,
    /// Representative timestamp for this window
    
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    /// Total blocks in this window
    
    #[serde(rename = "totalBlocks")]
    pub total_blocks: i32,
    /// Number of unique miners in this window
    
    #[serde(rename = "uniqueMiners")]
    pub unique_miners: i32,
    /// Total unique miners up to this window
    
    #[serde(rename = "totalUniqueMiners", skip_serializing_if = "Option::is_none")]
    pub total_unique_miners: Option<i32>,
    /// Herfindahl-Hirschman Index (0=perfect competition, 1=monopoly)
    
    #[serde(rename = "herfindahlIndex")]
    pub herfindahl_index: f64,
    /// Share of blocks mined by top miner (0-1)
    
    #[serde(rename = "topMinerShare")]
    pub top_miner_share: f64,
    /// Combined share of blocks mined by top 3 miners (0-1)
    
    #[serde(rename = "top3Share", skip_serializing_if = "Option::is_none")]
    pub top3_share: Option<f64>,
    /// Combined share of blocks mined by top 10 miners (0-1)
    
    #[serde(rename = "top10Share", skip_serializing_if = "Option::is_none")]
    pub top10_share: Option<f64>,
    /// Top miners in this window
    
    #[serde(rename = "miners", skip_serializing_if = "Option::is_none")]
    pub miners: Option<Vec<models::MinerStats>>,
    /// Average difficulty during this window
    
    #[serde(rename = "avgDifficulty", skip_serializing_if = "Option::is_none")]
    pub avg_difficulty: Option<f64>,
}

impl MiningDecentralizationWindow {
    pub fn new(start_height: i32, end_height: i32, timestamp: i32, total_blocks: i32, unique_miners: i32, herfindahl_index: f64, top_miner_share: f64) -> MiningDecentralizationWindow {
        MiningDecentralizationWindow {
            start_height,
            end_height,
            timestamp,
            total_blocks,
            unique_miners,
            total_unique_miners: None,
            herfindahl_index,
            top_miner_share,
            top3_share: None,
            top10_share: None,
            miners: None,
            avg_difficulty: None,
        }
    }
}

