/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkHealthSummaryResponse {
    /// Current blockchain height
    
    #[serde(rename = "currentHeight")]
    pub current_height: i32,
    /// Overall decentralization health score (0-100)
    
    #[serde(rename = "decentralizationScore")]
    pub decentralization_score: f64,
    
    #[serde(rename = "mining")]
    pub mining: Box<models::NetworkHealthSummaryResponseMining>,
    
    #[serde(rename = "wallets")]
    pub wallets: Box<models::NetworkHealthSummaryResponseWallets>,
}

impl NetworkHealthSummaryResponse {
    pub fn new(current_height: i32, decentralization_score: f64, mining: models::NetworkHealthSummaryResponseMining, wallets: models::NetworkHealthSummaryResponseWallets) -> NetworkHealthSummaryResponse {
        NetworkHealthSummaryResponse {
            current_height,
            decentralization_score,
            mining: Box::new(mining),
            wallets: Box::new(wallets),
        }
    }
}

