/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkHealthSummaryResponseMining {
    
    #[serde(rename = "last100Blocks")]
    pub last100_blocks: Box<models::MiningDecentralizationWindow>,
    
    #[serde(rename = "last1000Blocks")]
    pub last1000_blocks: Box<models::MiningDecentralizationWindow>,
}

impl NetworkHealthSummaryResponseMining {
    pub fn new(last100_blocks: models::MiningDecentralizationWindow, last1000_blocks: models::MiningDecentralizationWindow) -> NetworkHealthSummaryResponseMining {
        NetworkHealthSummaryResponseMining {
            last100_blocks: Box::new(last100_blocks),
            last1000_blocks: Box::new(last1000_blocks),
        }
    }
}

