/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotesResponse {
    
    #[serde(rename = "nicks")]
    pub nicks: i64,
    
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<models::NoteObject>>,
    
    #[serde(rename = "multisig", skip_serializing_if = "Option::is_none")]
    pub multisig: Option<Vec<models::NoteObject>>,
}

impl NotesResponse {
    pub fn new(nicks: i64) -> NotesResponse {
        NotesResponse {
            nicks,
            notes: None,
            multisig: None,
        }
    }
}

