/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoteName {
    /// Base58-encoded hash (5-tuple format)
    
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// Base58-encoded hash (5-tuple format)
    
    #[serde(rename = "lastName")]
    pub last_name: String,
}

impl NoteName {
    pub fn new(first_name: String, last_name: String) -> NoteName {
        NoteName {
            first_name,
            last_name,
        }
    }
}

