/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Note {
    /// Note version number
    
    #[serde(rename = "version")]
    pub version: i32,
    /// Block height where note was created
    
    #[serde(rename = "originPage")]
    pub origin_page: i32,
    /// Optional timelock constraints
    
    #[serde(rename = "timelock", skip_serializing_if = "Option::is_none")]
    pub timelock: Option<Box<models::Timelocks>>,
    /// Unique note identifier
    
    #[serde(rename = "name")]
    pub name: Box<models::NoteName>,
    /// Lock controlling spending of this note
    
    #[serde(rename = "lock")]
    pub lock: Box<models::Lock>,
    /// Base58-encoded hash (5-tuple format)
    
    #[serde(rename = "sourceHash")]
    pub source_hash: String,
    /// Whether this is a coinbase note
    
    #[serde(rename = "isCoinbase")]
    pub is_coinbase: bool,
    /// Amount of assets in this note
    
    #[serde(rename = "assets")]
    pub assets: i64,
}

impl Note {
    pub fn new(version: i32, origin_page: i32, name: models::NoteName, lock: models::Lock, source_hash: String, is_coinbase: bool, assets: i64) -> Note {
        Note {
            version,
            origin_page,
            timelock: None,
            name: Box::new(name),
            lock: Box::new(lock),
            source_hash,
            is_coinbase,
            assets,
        }
    }
}

