/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputSource {
    /// Base58-encoded hash (5-tuple format)
    
    #[serde(rename = "sourceHash")]
    pub source_hash: String,
    /// True if the note is from a coinbase transaction.
    
    #[serde(rename = "isCoinbase")]
    pub is_coinbase: bool,
}

impl OutputSource {
    pub fn new(source_hash: String, is_coinbase: bool) -> OutputSource {
        OutputSource {
            source_hash,
            is_coinbase,
        }
    }
}

