/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageSummary {
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "digest")]
    pub digest: String,
    /// Block timestamp
    
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    /// Counter within current epoch
    
    #[serde(rename = "epochCounter")]
    pub epoch_counter: i32,
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "target")]
    pub target: String,
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "accumulatedWork")]
    pub accumulated_work: String,
    /// Block height
    
    #[serde(rename = "height")]
    pub height: i32,
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "parent")]
    pub parent: String,
}

impl PageSummary {
    pub fn new(digest: String, timestamp: i32, epoch_counter: i32, target: String, accumulated_work: String, height: i32, parent: String) -> PageSummary {
        PageSummary {
            digest,
            timestamp,
            epoch_counter,
            target,
            accumulated_work,
            height,
            parent,
        }
    }
}

