/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationInfo {
    
    #[serde(rename = "limit")]
    pub limit: i32,
    
    #[serde(rename = "offset")]
    pub offset: i32,
    /// Whether there are more items available
    
    #[serde(rename = "hasMore")]
    pub has_more: bool,
}

impl PaginationInfo {
    pub fn new(limit: i32, offset: i32, has_more: bool) -> PaginationInfo {
        PaginationInfo {
            limit,
            offset,
            has_more,
        }
    }
}

