/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofRateHistoryResponse {
    
    #[serde(rename = "data")]
    pub data: Vec<models::ProofRateDataPoint>,
}

impl ProofRateHistoryResponse {
    pub fn new(data: Vec<models::ProofRateDataPoint>) -> ProofRateHistoryResponse {
        ProofRateHistoryResponse {
            data,
        }
    }
}

