/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofRateDataPoint {
    
    #[serde(rename = "height")]
    pub height: i32,
    
    #[serde(rename = "proofrate")]
    pub proofrate: f64,
    
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    
    #[serde(rename = "timeDelta", skip_serializing_if = "Option::is_none")]
    pub time_delta: Option<i32>,
    
    #[serde(rename = "difficultyAdjustment", skip_serializing_if = "Option::is_none")]
    pub difficulty_adjustment: Option<f64>,
}

impl ProofRateDataPoint {
    pub fn new(height: i32, proofrate: f64, timestamp: i64) -> ProofRateDataPoint {
        ProofRateDataPoint {
            height,
            proofrate,
            timestamp,
            time_delta: None,
            difficulty_adjustment: None,
        }
    }
}

