/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RangeParam {
    
    #[serde(rename = "startHeight")]
    pub start_height: i32,
    
    #[serde(rename = "endHeight")]
    pub end_height: i32,
}

impl RangeParam {
    pub fn new(start_height: i32, end_height: i32) -> RangeParam {
        RangeParam {
            start_height,
            end_height,
        }
    }
}

