/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Seed {
    /// Lock that controls the recipient note
    
    #[serde(rename = "recipient")]
    pub recipient: Box<models::Lock>,
    /// Amount of assets (coins) transferred
    
    #[serde(rename = "gift")]
    pub gift: i64,
    /// Base58-encoded hash (5-tuple format)
    
    #[serde(rename = "parentHash")]
    pub parent_hash: String,
    /// Optional timelock constraints
    
    #[serde(rename = "timelockIntent")]
    pub timelock_intent: Box<models::Timelocks>,
    /// Hash of source note or block plus coinbase bool
    
    #[serde(rename = "outputSource")]
    pub output_source: Box<models::OutputSource>,
}

impl Seed {
    pub fn new(recipient: models::Lock, gift: i64, parent_hash: String, timelock_intent: models::Timelocks, output_source: models::OutputSource) -> Seed {
        Seed {
            recipient: Box::new(recipient),
            gift,
            parent_hash,
            timelock_intent: Box::new(timelock_intent),
            output_source: Box::new(output_source),
        }
    }
}

