/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Signature {
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "pubkey")]
    pub pubkey: String,
    /// 8 u64 values as strings
    
    #[serde(rename = "chal")]
    pub chal: Vec<String>,
    /// 8 u64 values as strings
    
    #[serde(rename = "sig")]
    pub sig: Vec<String>,
}

impl Signature {
    pub fn new(pubkey: String, chal: Vec<String>, sig: Vec<String>) -> Signature {
        Signature {
            pubkey,
            chal,
            sig,
        }
    }
}

