/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Spend {
    /// Whether this spend has a signature
    
    #[serde(rename = "hasSignature")]
    pub has_signature: bool,
    
    #[serde(rename = "signatures")]
    pub signatures: Vec<models::Signature>,
    /// Seeds defining where assets go
    
    #[serde(rename = "seeds")]
    pub seeds: Vec<models::Seed>,
    /// Transaction fee paid
    
    #[serde(rename = "fee")]
    pub fee: i64,
}

impl Spend {
    pub fn new(has_signature: bool, signatures: Vec<models::Signature>, seeds: Vec<models::Seed>, fee: i64) -> Spend {
        Spend {
            has_signature,
            signatures,
            seeds,
            fee,
        }
    }
}

