/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimestampRangeParam {
    
    #[serde(rename = "startTimestamp")]
    pub start_timestamp: i32,
    
    #[serde(rename = "endTimestamp")]
    pub end_timestamp: i32,
}

impl TimestampRangeParam {
    pub fn new(start_timestamp: i32, end_timestamp: i32) -> TimestampRangeParam {
        TimestampRangeParam {
            start_timestamp,
            end_timestamp,
        }
    }
}

