/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TipObject {
    /// Tip block hash as base58
    
    #[serde(rename = "hash")]
    pub hash: String,
    /// Tip block height
    
    #[serde(rename = "height")]
    pub height: i32,
}

impl TipObject {
    pub fn new(hash: String, height: i32) -> TipObject {
        TipObject {
            hash,
            height,
        }
    }
}

