/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionParam {
    /// Whole signed transaction serialized and Base58-encoded
    
    #[serde(rename = "rawTransaction")]
    pub raw_transaction: String,
}

impl TransactionParam {
    pub fn new(raw_transaction: String) -> TransactionParam {
        TransactionParam {
            raw_transaction,
        }
    }
}

