/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionOutput {
    /// The output note being created
    
    #[serde(rename = "note")]
    pub note: Box<models::Note>,
    /// Seeds that created this output
    
    #[serde(rename = "seeds")]
    pub seeds: Vec<models::Seed>,
}

impl TransactionOutput {
    pub fn new(note: models::Note, seeds: Vec<models::Seed>) -> TransactionOutput {
        TransactionOutput {
            note: Box::new(note),
            seeds,
        }
    }
}

