/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsResponse {
    /// Array of transactions with block information
    
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::TransactionWithBlockInfo>,
    /// Total number of transactions available
    
    #[serde(rename = "totalCount")]
    pub total_count: i32,
    /// Pagination information (present when using limit/offset)
    
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::PaginationInfo>>,
}

impl TransactionsResponse {
    pub fn new(transactions: Vec<models::TransactionWithBlockInfo>, total_count: i32) -> TransactionsResponse {
        TransactionsResponse {
            transactions,
            total_count,
            pagination: None,
        }
    }
}

