/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionWithBlockInfo {
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "txId")]
    pub tx_id: String,
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "blockId")]
    pub block_id: String,
    /// Natural number representing block height
    
    #[serde(rename = "blockHeight", skip_serializing_if = "Option::is_none")]
    pub block_height: Option<i32>,
    /// Natural number representing Unix epoch time
    
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    /// The transaction details
    
    #[serde(rename = "transaction")]
    pub transaction: Box<models::TransactionObject>,
}

impl TransactionWithBlockInfo {
    pub fn new(tx_id: String, block_id: String, transaction: models::TransactionObject) -> TransactionWithBlockInfo {
        TransactionWithBlockInfo {
            tx_id,
            block_id,
            block_height: None,
            timestamp: None,
            transaction: Box::new(transaction),
        }
    }
}

