/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionInput {
    /// The note being spent
    
    #[serde(rename = "note")]
    pub note: Box<models::Note>,
    /// The spend authorization
    
    #[serde(rename = "spend")]
    pub spend: Box<models::Spend>,
}

impl TransactionInput {
    pub fn new(note: models::Note, spend: models::Spend) -> TransactionInput {
        TransactionInput {
            note: Box::new(note),
            spend: Box::new(spend),
        }
    }
}

