/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionObject {
    /// Base58-encoded identifier used in Nockchain
    
    #[serde(rename = "id")]
    pub id: String,
    
    #[serde(rename = "inputs")]
    pub inputs: Vec<models::TransactionInput>,
    
    #[serde(rename = "outputs")]
    pub outputs: Vec<models::TransactionOutput>,
    /// Total fees in smallest unit (atoms)
    
    #[serde(rename = "totalFees")]
    pub total_fees: i64,
    /// Transaction size in bytes
    
    #[serde(rename = "totalSize")]
    pub total_size: i64,
    /// Combined timelock range from all inputs
    
    #[serde(rename = "timelocks", skip_serializing_if = "Option::is_none")]
    pub timelocks: Option<Box<models::Timelocks>>,
}

impl TransactionObject {
    pub fn new(id: String, inputs: Vec<models::TransactionInput>, outputs: Vec<models::TransactionOutput>, total_fees: i64, total_size: i64) -> TransactionObject {
        TransactionObject {
            id,
            inputs,
            outputs,
            total_fees,
            total_size,
            timelocks: None,
        }
    }
}

