/*
 * Nockchain JSON-RPC
 *
 * RPC surface for Nockchain. Pokes and peeks over HTTP. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletGrowthWindow {
    /// Starting block height of this window
    
    #[serde(rename = "startHeight")]
    pub start_height: i32,
    /// Ending block height of this window
    
    #[serde(rename = "endHeight")]
    pub end_height: i32,
    /// Representative timestamp for this window
    
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    /// Total unique addresses that have ever been active up to this point
    
    #[serde(rename = "totalUniqueAddresses")]
    pub total_unique_addresses: i32,
    /// New addresses that first appeared in this window
    
    #[serde(rename = "newAddressesInWindow")]
    pub new_addresses_in_window: i32,
    /// Number of addresses with positive balance at end of window
    
    #[serde(rename = "activeWalletsWithBalance")]
    pub active_wallets_with_balance: i32,
    /// New addresses per block in this window
    
    #[serde(rename = "growthRate", skip_serializing_if = "Option::is_none")]
    pub growth_rate: Option<f64>,
    /// Total addresses per block since genesis
    
    #[serde(rename = "cumulativeGrowthRate", skip_serializing_if = "Option::is_none")]
    pub cumulative_growth_rate: Option<f64>,
}

impl WalletGrowthWindow {
    pub fn new(start_height: i32, end_height: i32, timestamp: i32, total_unique_addresses: i32, new_addresses_in_window: i32, active_wallets_with_balance: i32) -> WalletGrowthWindow {
        WalletGrowthWindow {
            start_height,
            end_height,
            timestamp,
            total_unique_addresses,
            new_addresses_in_window,
            active_wallets_with_balance,
            growth_rate: None,
            cumulative_growth_rate: None,
        }
    }
}

