/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/rpc/v1': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Nockchain JSON-RPC v1 endpoint */
    post: operations['rpcV1'];
    delete?: never;
    /** Handle CORS preflight requests */
    options: operations['rpcV1Options'];
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    JsonRpcRequestEnvelope:
      | components['schemas']['GetBlocksByHeightRequest']
      | components['schemas']['GetBlocksByIdRequest']
      | components['schemas']['GetBlockIdsByHeightRequest']
      | components['schemas']['GetBlocksByTimestampRangeRequest']
      | components['schemas']['GetTipRequest']
      | components['schemas']['GetNotesByAddressRequest']
      | components['schemas']['GetNotesByFirstNameRequest']
      | components['schemas']['GetNotesFromBlocksRequest']
      | components['schemas']['GetNotesInAssetRangeRequest']
      | components['schemas']['GetTransactionsByAddressRequest']
      | components['schemas']['GetTransactionsByBlockIdRequest']
      | components['schemas']['GetTransactionsByBlockHeightRequest']
      | components['schemas']['GetTransactionByTxidRequest'];
    GetBlocksByHeightRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlocksByHeight';
      id: string | number | null;
      params: components['schemas']['GetBlocksByHeightParams'][];
    };
    GetBlocksByIdRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlocksById';
      id: string | number | null;
      params: components['schemas']['GetBlocksByIdParams'][];
    };
    GetBlockIdsByHeightRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlockIdsByHeight';
      id: string | number | null;
      params: components['schemas']['GetBlockIdsByHeightParams'][];
    };
    GetBlocksByTimestampRangeRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlocksByTimestampRange';
      id: string | number | null;
      params: components['schemas']['GetBlocksByTimestampRangeParams'][];
    };
    GetTipRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTip';
      id: string | number | null;
      params?: components['schemas']['GetTipParams'][];
    };
    GetNotesByAddressRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getNotesByAddress';
      id: string | number | null;
      params: components['schemas']['GetNotesByAddressParams'][];
    };
    GetNotesByFirstNameRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getNotesByFirstName';
      id: string | number | null;
      params: components['schemas']['GetNotesByFirstNameParams'][];
    };
    GetNotesFromBlocksRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getNotesFromBlocks';
      id: string | number | null;
      params: components['schemas']['GetNotesFromBlocksParams'][];
    };
    GetNotesInAssetRangeRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getNotesInAssetRange';
      id: string | number | null;
      params: components['schemas']['GetNotesInAssetRangeParams'][];
    };
    GetTransactionsByAddressRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionsByAddress';
      id: string | number | null;
      params: components['schemas']['GetTransactionsByAddressParams'][];
    };
    GetTransactionsByBlockIdRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionsByBlockId';
      id: string | number | null;
      params: components['schemas']['GetTransactionsByBlockIdParams'][];
    };
    GetTransactionsByBlockHeightRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionsByBlockHeight';
      id: string | number | null;
      params: components['schemas']['GetTransactionsByBlockHeightParams'][];
    };
    GetTransactionByTxidRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionByTxid';
      id: string | number | null;
      params: components['schemas']['GetTransactionByTxidParams'][];
    };
    GetBlocksByHeightParams: {
      /** @description Array of block heights to query */
      heights: number[];
      /** @description Whether to include full transaction data */
      includeTransactions?: boolean | null;
    };
    GetBlocksByIdParams: {
      /** @description Array of block IDs (base58) to query */
      blockIds: string[];
      /** @description Whether to include full transaction data */
      includeTransactions?: boolean | null;
    };
    GetBlockIdsByHeightParams: {
      /** @description Array of block heights */
      heights: number[];
    };
    GetBlocksByTimestampRangeParams: {
      /**
       * Format: int64
       * @description Minimum timestamp (Unix seconds)
       */
      minTimestamp: number;
      /**
       * Format: int64
       * @description Maximum timestamp (Unix seconds)
       */
      maxTimestamp: number;
      /** @description Whether to include full transaction data */
      includeTransactions?: boolean | null;
    };
    GetTipParams: {
      /** @description Whether to include full transaction data */
      includeTransactions?: boolean | null;
    };
    GetNotesByAddressParams: {
      /** @description Address to query (base58) */
      address: string;
      /** @description Whether to include spent notes */
      showSpent?: boolean | null;
    };
    GetNotesByFirstNameParams: {
      /** @description First name of notes to query (base58) */
      firstName: string;
      /** @description Whether to include spent notes */
      showSpent?: boolean | null;
    };
    GetNotesFromBlocksParams: {
      /** @description Array of block IDs (base58) */
      blockIds: string[];
      /** @description Whether to include spent notes */
      showSpent?: boolean | null;
    };
    GetNotesInAssetRangeParams: {
      /**
       * Format: int64
       * @description Minimum asset amount
       */
      minAsset: number;
      /**
       * Format: int64
       * @description Maximum asset amount
       */
      maxAsset: number;
      /** @description Whether to include spent notes */
      showSpent?: boolean | null;
    };
    GetTransactionsByAddressParams: {
      /** @description Address to query (base58) */
      address: string;
    };
    GetTransactionsByBlockIdParams: {
      /** @description Block ID (base58) */
      blockId: string;
    };
    GetTransactionsByBlockHeightParams: {
      /** @description Block height */
      height: number;
    };
    GetTransactionByTxidParams: {
      /** @description Transaction ID (base58) */
      transactionId: string;
    };
    /** @description Standard JSON-RPC 2.0 response.
     *     Exactly **one** of `result` or `error` MUST appear.
     *      */
    JsonRpcResponseEnvelope: {
      /** @constant */
      jsonrpc: '2.0';
      /** @description Successful result payload (method-specific) */
      result?:
        | components['schemas']['BlockObjectV1'][]
        | string[]
        | components['schemas']['NoteObjectV1'][]
        | components['schemas']['TransactionObjectV1'][]
        | components['schemas']['BlockObjectV1']
        | components['schemas']['TransactionObjectV1'];
      error?: components['schemas']['JsonRpcError'];
      /** @description Mirrors the `id` sent in the request */
      id: string | number | null;
    };
    JsonRpcError: {
      /** @description Short description */
      message: string;
      /** @description Optional extra diagnostic information */
      data?: unknown;
    };
    TransportError: {
      /** @example 400 */
      code: string;
      message: string;
      details?: string | null;
    };
    BlockObjectV1: {
      /** @description Block version number */
      version: number;
      /** @description Block hash/digest as base58 string */
      digest: string;
      /**
       * Format: uri
       * @description URL to the proof for this block
       */
      proofUrl: string;
      /** @description Parent block hash as base58 string */
      parent: string;
      /** @description Array of transaction IDs (base58) */
      txids: string[];
      /** @description Array of coinbase note objects */
      coinbaseNotes: components['schemas']['NoteObjectV1'][];
      /**
       * Format: int64
       * @description Block timestamp in Unix seconds
       */
      timestamp: number;
      /**
       * Format: int64
       * @description Counter within the current epoch
       */
      epochCounter: number;
      /** @description Total accumulated work as string */
      accumulatedWork: string;
      /** @description Mining target as string */
      target: string;
      /**
       * Format: int64
       * @description Block height in the chain
       */
      height: number;
      /** @description Optional message included in the block */
      msg: string;
      /** @description Optional array of full transaction objects (only if includeTransactions was true) */
      transactionsData?: components['schemas']['TransactionObjectV1'][] | null;
    };
    NoteObjectV1: components['schemas']['NoteV0Object'] | components['schemas']['NoteV1Object'];
    NoteV0Object: {
      /**
       * @description Note version (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      version: '0';
      /**
       * Format: int64
       * @description Block height where note originated
       */
      originPage: number;
      /** @description Block ID as base58 string */
      blockId: string;
      /** @description Timelock constraints */
      timelock?: components['schemas']['TimelockV0'];
      /** @description First component of note name (base58) */
      firstName: string;
      /** @description Second component of note name (base58) */
      lastName: string;
      /** @description Lock controlling the note */
      lock: components['schemas']['LockObject'];
      /** @description Source hash (base58) */
      sourceHash: string;
      /** @description Whether this is a coinbase note */
      isCoinbase: boolean;
      /**
       * Format: int64
       * @description Amount of assets in this note
       */
      assets: number;
      /** @description Transaction ID where this note was spent (null if unspent) */
      spentOn?: string | null;
    };
    NoteV1Object: {
      /**
       * @description Note version (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      version: '1';
      /**
       * Format: int64
       * @description Block height where note originated
       */
      originPage: number;
      /** @description First component of note name (base58) */
      firstName: string;
      /** @description Second component of note name (base58) */
      lastName: string;
      /** @description Map of keys to values. Special keys are processed:
       *     - "lock": Object with {version: u64, data: [LockPrimitiveObject]}
       *     - Other keys: Base64-encoded bytes (string)
       *      */
      noteData: {
        [key: string]: unknown;
      };
      /**
       * Format: int64
       * @description Amount of assets in this note
       */
      assets: number;
      /** @description Whether this is a coinbase note */
      isCoinbase: boolean;
      /** @description Transaction ID where this note was spent (null if unspent) */
      spentOn?: string | null;
    };
    TimelockV0: {
      absolute: components['schemas']['TimelockRange'];
      relative: components['schemas']['TimelockRange'];
    };
    TimelockRange: {
      /** Format: int64 */
      min?: number | null;
      /** Format: int64 */
      max?: number | null;
    };
    LockObject: {
      /** @description Number of signatures required */
      m: number;
      /** @description Array of public keys (base58) */
      pubkeys: string[];
    };
    TransactionObjectV1:
      | components['schemas']['TransactionV0Object']
      | components['schemas']['TransactionV1Object'];
    TransactionV0Object: {
      /**
       * @description Transaction version (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      version: '0';
      /** @description Transaction ID (base58) */
      id: string;
      /**
       * Format: int64
       * @description Total size of transaction
       */
      totalSize: number;
      /**
       * Format: int64
       * @description Total fees paid
       */
      totalFees: number;
      timelockRange: {
        /** Format: int64 */
        min?: number | null;
        /** Format: int64 */
        max?: number | null;
      };
      outputs: components['schemas']['TransactionOutputV0Object'][];
      inputs: components['schemas']['TransactionInputV0Object'][];
      /** @description Block ID containing this transaction (base58) */
      blockId: string;
    };
    TransactionInputV0Object: {
      /** @description First name of input note (base58) */
      firstName: string;
      /** @description Last name of input note (base58) */
      lastName: string;
      spend: components['schemas']['SpendV0Object'];
    };
    SpendV0Object: {
      signature: components['schemas']['SignatureV0Object'][];
      seeds: components['schemas']['SeedV0Object'][];
      /** Format: int64 */
      fee: number;
    };
    SignatureV0Object: {
      /** @description Public key (base58) */
      pubkey: string;
      /** @description Challenge values (8 u64 as strings) */
      chal: string[];
      /** @description Signature values (8 u64 as strings) */
      sig: string[];
    };
    TransactionOutputV0Object: {
      /** @description First name of output note (base58) */
      firstName: string;
      /** @description Last name of output note (base58) */
      lastName: string;
      seeds: components['schemas']['SeedV0Object'][];
    };
    SeedV0Object: {
      /** @description Output source hash (base58), null if no source */
      outputSourceHash?: string | null;
      recipientLock: components['schemas']['LockObject'];
      timelockIntent?: components['schemas']['TimelockV0'];
      /** Format: int64 */
      gift: number;
      /** @description Parent hash (base58) */
      parentHash: string;
    };
    TransactionV1Object: {
      /**
       * @description Transaction version (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      version: '1';
      /** @description Transaction ID (base58) */
      id: string;
      /**
       * Format: int64
       * @description Total size of transaction
       */
      totalSize: number;
      outputs: components['schemas']['TransactionOutputV1Object'][];
      spends: components['schemas']['SpendV1Object'][];
      /** @description Block ID containing this transaction (base58) */
      blockId: string;
    };
    TransactionOutputV1Object: {
      /** @description First name of output note (base58) */
      firstName: string;
      /** @description Last name of output note (base58) */
      lastName: string;
      seeds: components['schemas']['SeedV1Object'][];
    };
    SpendV1Object: {
      /** @description First name of spent note (base58) */
      firstName: string;
      /** @description Last name of spent note (base58) */
      lastName: string;
      /**
       * @description Spend version - v1 uses witness, v0_to_v1 uses signaturesV0
       * @enum {string}
       */
      version: 'v1' | 'v0_to_v1';
      /** @description V1 witness data (only present for version=v1) */
      witness?: components['schemas']['WitnessObject'];
      /** @description V0 signatures (only present for version=v0_to_v1) */
      signaturesV0?: components['schemas']['SignatureV0Object'][] | null;
      seeds: components['schemas']['SeedV1Object'][];
      /** Format: int64 */
      fee: number;
    };
    WitnessObject: {
      lockMerkleProof: components['schemas']['LockMerkleProofObject'];
      /** @description Array of PKH signatures */
      pkhSignature: components['schemas']['PkhSignatureObject'][];
      /** @description Map of keys to base64-encoded bytes */
      hax: {
        [key: string]: string;
      };
      /** Format: int64 */
      tim: number;
    };
    PkhSignatureObject: {
      /** @description Public key (base58) */
      pubkey: string;
      /** @description Challenge values (8 u64 as strings) */
      chal: string[];
      /** @description Signature values (8 u64 as strings) */
      sig: string[];
    };
    LockMerkleProofObject: {
      spendCondition: components['schemas']['LockPrimitiveObject'][];
      /** Format: int64 */
      axis: number;
      /** @description Merkle root (base58) */
      merkleProofRoot: string;
      /** @description Merkle path (array of base58 strings) */
      merkleProofPath: string[];
    };
    /** @description Lock primitive - exactly one property should be present */
    LockPrimitiveObject: {
      pkh?: {
        m?: number;
        h?: string[];
      };
      tim?: {
        relative?: {
          /** Format: int64 */
          min?: number | null;
          /** Format: int64 */
          max?: number | null;
        };
        absolute?: {
          /** Format: int64 */
          min?: number | null;
          /** Format: int64 */
          max?: number | null;
        };
      };
      hax?: string[];
      brn?: null;
    };
    SeedV1Object: {
      /** @description Output hash (base58), null if no source */
      outputHash?: string | null;
      isCoinbase: boolean;
      /** @description Lock merkle root (base58) */
      lockRoot: string;
      /** @description Map of keys to values. Special keys are processed:
       *     - "lock": Object with {version: u64, data: [LockPrimitiveObject]}
       *     - Other keys: Base64-encoded bytes (string)
       *      */
      noteData: {
        [key: string]: unknown;
      };
      /** Format: int64 */
      gift: number;
      /** @description Parent hash (base58) */
      parentHash: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  rpcV1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JsonRpcRequestEnvelope'];
      };
    };
    responses: {
      /** @description JSON-RPC success or error response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonRpcResponseEnvelope'];
        };
      };
      /** @description Transport-level error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransportError'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransportError'];
        };
      };
    };
  };
  rpcV1Options: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CORS preflight response */
      200: {
        headers: {
          /** @example * */
          'Access-Control-Allow-Origin'?: string;
          /** @example GET, POST, OPTIONS */
          'Access-Control-Allow-Methods'?: string;
          /** @example Content-Type, Accept, Authorization */
          'Access-Control-Allow-Headers'?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
