/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/rpc': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Nockchain JSON-RPC endpoint */
    post: operations['rpc'];
    delete?: never;
    /** Handle CORS preflight requests */
    options: operations['rpcOptions'];
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    JsonRpcRequestEnvelope:
      | components['schemas']['GetBlockByHeightRequest']
      | components['schemas']['GetBlockByHashRequest']
      | components['schemas']['GetBlocksByRangeRequest']
      | components['schemas']['GetBlocksByTimestampRangeRequest']
      | components['schemas']['GetTipRequest']
      | components['schemas']['GetHeightRequest']
      | components['schemas']['GetTransactionByIdRequest']
      | components['schemas']['GetAllTransactionsRequest']
      | components['schemas']['GetTransactionsByAddressRequest']
      | components['schemas']['GetRawTransactionByIdRequest']
      | components['schemas']['GetBalanceByAddressRequest']
      | components['schemas']['GetMiningPubkeysRequest']
      | components['schemas']['GetHeavySummaryRequest']
      | components['schemas']['IsMainnetRequest']
      | components['schemas']['SubmitTransactionRequest']
      | components['schemas']['GetBlockchainMetricsRequest']
      | components['schemas']['GetTransactionsByBlockIdRequest']
      | components['schemas']['GetTransactionsByBlockHeightRequest']
      | components['schemas']['GetDecentralizationMetricsRequest']
      | components['schemas']['GetNetworkHealthSummaryRequest']
      | components['schemas']['GetMiningDecentralizationRequest']
      | components['schemas']['GetWalletGrowthMetricsRequest']
      | components['schemas']['GetNotesRequest']
      | components['schemas']['GetProofRateHistoryRequest']
      | components['schemas']['GetAddressesWithBalanceRequest'];
    GetBlockByHeightRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlockByHeight';
      id: string | number | null;
      params: components['schemas']['GetBlockByHeightParams'];
    };
    GetBlockByHashRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlockByHash';
      id: string | number | null;
      params: components['schemas']['GetBlockByHashParams'];
    };
    GetBlocksByRangeRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlocksByRange';
      id: string | number | null;
      params: components['schemas']['GetBlocksByRangeParams'];
    };
    GetBlocksByTimestampRangeRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlocksByTimestampRange';
      id: string | number | null;
      params: components['schemas']['GetBlocksByTimestampRangeParams'];
    };
    GetTipRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTip';
      id: string | number | null;
      params?: components['schemas']['EmptyParams'];
    };
    GetHeightRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getHeight';
      id: string | number | null;
      params?: components['schemas']['EmptyParams'];
    };
    GetTransactionByIdRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionById';
      id: string | number | null;
      params: components['schemas']['GetTransactionByIdParams'];
    };
    GetAllTransactionsRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getAllTransactions';
      id: string | number | null;
      params?: components['schemas']['GetAllTransactionsParams'];
    };
    GetTransactionsByAddressRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionsByAddress';
      id: string | number | null;
      params: components['schemas']['GetTransactionsByAddressParams'];
    };
    GetRawTransactionByIdRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getRawTransactionById';
      id: string | number | null;
      params: components['schemas']['GetTransactionByIdParams'];
    };
    GetBalanceByAddressRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBalanceByAddress';
      id: string | number | null;
      params: components['schemas']['GetTransactionByIdParams'];
    };
    GetMiningPubkeysRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getMiningPubkeys';
      id: string | number | null;
      params?: components['schemas']['EmptyParams'];
    };
    GetHeavySummaryRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getHeavySummary';
      id: string | number | null;
      params?: components['schemas']['EmptyParams'];
    };
    IsMainnetRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'isMainnet';
      id: string | number | null;
      params?: components['schemas']['EmptyParams'];
    };
    SubmitTransactionRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'submitTransaction';
      id: string | number | null;
      params: components['schemas']['SubmitTransactionParams'];
    };
    GetBlockchainMetricsRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getBlockchainMetrics';
      id: string | number | null;
      params?: components['schemas']['GetBlockchainMetricsParams'];
    };
    GetTransactionsByBlockIdRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionsByBlockId';
      id: string | number | null;
      params: components['schemas']['GetTransactionsByBlockIdParams'];
    };
    GetTransactionsByBlockHeightRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getTransactionsByBlockHeight';
      id: string | number | null;
      params: components['schemas']['GetTransactionsByBlockHeightParams'];
    };
    GetDecentralizationMetricsRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getDecentralizationMetrics';
      id: string | number | null;
      params?: components['schemas']['GetDecentralizationMetricsParams'];
    };
    GetNetworkHealthSummaryRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getNetworkHealthSummary';
      id: string | number | null;
      params?: components['schemas']['GetNetworkHealthSummaryParams'];
    };
    GetMiningDecentralizationRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getMiningDecentralization';
      id: string | number | null;
      params?: components['schemas']['GetMiningDecentralizationParams'];
    };
    GetWalletGrowthMetricsRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getWalletGrowthMetrics';
      id: string | number | null;
      params?: components['schemas']['GetWalletGrowthMetricsParams'];
    };
    GetProofRateHistoryRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getProofRateHistory';
      id: string | number | null;
      params: components['schemas']['GetProofRateHistoryParams'];
    };
    GetAddressesWithBalanceRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getAddressesWithBalance';
      id: string | number | null;
      params?: components['schemas']['GetAddressesWithBalanceParams'];
    };
    /** @description Standard JSON-RPC 2.0 response.
     *     Exactly **one** of `result` or `error` MUST appear.
     *      */
    JsonRpcResponseEnvelope: {
      /** @constant */
      jsonrpc: '2.0';
      /** @description Current tip block height for this node */
      tip?: number;
      /** @description Successful result payload (method-specific). */
      result?:
        | components['schemas']['BlockObject']
        | components['schemas']['TipObject']
        | components['schemas']['HeightObject']
        | components['schemas']['TransactionObject']
        | components['schemas']['TransactionsResponse']
        | components['schemas']['RawTransactionObject']
        | components['schemas']['AddressTransactionsResponse']
        | components['schemas']['BlocksRangeResponse']
        | components['schemas']['BalanceObject']
        | components['schemas']['MiningPubkeysArray']
        | components['schemas']['HeavySummaryObject']
        | components['schemas']['BooleanResult']
        | components['schemas']['TransactionId']
        | components['schemas']['TransactionWithBlockInfo']
        | components['schemas']['DecentralizationMetricsResponse']
        | components['schemas']['NetworkHealthSummaryResponse']
        | components['schemas']['MiningDecentralizationResponse']
        | components['schemas']['WalletGrowthMetricsResponse']
        | components['schemas']['ProofRateHistoryResponse']
        | components['schemas']['NotesResponse']
        | components['schemas']['AddressesWithBalanceResponse'];
      error?: components['schemas']['JsonRpcError'];
      /** @description Mirrors the `id` sent in the request */
      id: string | number | null;
    };
    JsonRpcError: {
      /** @description Short description. */
      message: string;
      /** @description Optional extra diagnostic information. */
      data?: unknown;
    };
    TransportError: {
      /** @example 400 */
      code: string;
      message: string;
      details?: string | null;
    };
    HeightParam: {
      height: number;
    };
    HeightWithPreviousParam: {
      height: number;
      previousCount: number;
    };
    RangeParam: {
      startHeight: number;
      endHeight: number;
    };
    TimestampRangeParam: {
      startTimestamp: number;
      endTimestamp: number;
    };
    HashParam: {
      hash: components['schemas']['BlockHash'];
    };
    AddressParam: {
      address: components['schemas']['Base58Address'];
    };
    IdParam: {
      id: string;
    };
    TransactionParam: {
      rawTransaction: components['schemas']['RawTransactionBase58'];
    };
    AddressTransactionsParam: {
      address: components['schemas']['Base58Address'];
      /** @description Maximum number of transactions to return */
      limit?: number;
      /** @description Number of transactions to skip (for pagination) */
      offset?: number;
      /** @description Only include transactions from this block height onwards */
      minHeight?: number | null;
      /** @description Only include transactions up to this block height */
      maxHeight?: number | null;
    };
    GetBlockByHeightParams: components['schemas']['HeightParam'][];
    GetBlockByHeightWithPreviousParams: components['schemas']['HeightWithPreviousParam'][];
    GetBlocksByRangeParams: components['schemas']['RangeParam'][];
    GetBlocksByTimestampRangeParams: components['schemas']['TimestampRangeParam'][];
    GetBlockByHashParams: components['schemas']['HashParam'][];
    GetTransactionsByAddressParams: components['schemas']['AddressTransactionsParam'][];
    GetTransactionByIdParams: components['schemas']['IdParam'][];
    GetTransactionsByBlockIdParams: {
      /** @description Block ID to query transactions for */
      id: string;
      /** @description Maximum number of transactions to return */
      limit?: number;
      /** @description Number of transactions to skip */
      offset?: number;
    }[];
    GetTransactionsByBlockHeightParams: {
      /** @description Block height to query transactions for */
      height: number;
      /** @description Maximum number of transactions to return */
      limit?: number;
      /** @description Number of transactions to skip */
      offset?: number;
    }[];
    GetAllTransactionsParams: components['schemas']['PaginationParam'][];
    GetMiningDecentralizationParams: {
      /** @description Starting block height for analysis (defaults to current_height - 50000) */
      startHeight?: number | null;
      /** @description Ending block height for analysis (defaults to current height) */
      endHeight?: number | null;
      /** @description Size of each analysis window in blocks */
      windowSize?: number | null;
      /** @description Maximum number of data points to return (for time series) */
      dataPoints?: number | null;
      /** @description Number of top miners to include in each window's detailed stats */
      topMinersCount?: number | null;
    }[];
    SubmitTransactionParams: components['schemas']['TransactionParam'][];
    GetBlockchainMetricsParams: {
      /** @description End block height to analyze (defaults to current tip) */
      blockHeight?: number | null;
      /** @description Start block height for range analysis (defaults to 0) */
      startHeight?: number | null;
      /** @description End block height for range analysis (defaults to current tip) */
      endHeight?: number | null;
      /** @description Size of chunks for proof rate history aggregation (auto-calculated if not provided) */
      chunkSize?: number | null;
    }[];
    GetDecentralizationMetricsParams: {
      /** @description Starting block height for analysis (defaults to 0) */
      startHeight?: number | null;
      /** @description Ending block height for analysis (defaults to current tip) */
      endHeight?: number | null;
      /** @description Size of each analysis window in blocks */
      windowSize?: number;
      /** @description Maximum number of data points to return (for time series) */
      dataPoints?: number;
    }[];
    GetNetworkHealthSummaryParams: {
      /** @description Block height to analyze (defaults to current tip) */
      height?: number | null;
    }[];
    GetWalletGrowthMetricsParams: {
      /** @description Starting block height for analysis */
      startHeight?: number | null;
      /** @description Ending block height for analysis */
      endHeight?: number | null;
      /** @description Size of each analysis window in blocks */
      windowSize?: number;
      /** @description Maximum number of data points to return */
      dataPoints?: number;
    }[];
    GetProofRateHistoryParams: {
      /** @description Starting block height for the history */
      startHeight?: number | null;
      /** @description Ending block height for the history */
      endHeight?: number | null;
      /** @description Maximum number of data points to return */
      maxSamples?: number | null;
      /**
       * @description The type of proofrate to return
       * @default raw
       * @enum {string|null}
       */
      smoothingType: 'raw' | 'smoothed_100' | 'smoothed_50' | null;
    }[];
    GetAddressesWithBalanceParamsInner: {
      limit?: number;
      offset?: number;
      /**
       * Format: int64
       * @description Filter addresses with at least this balance (default: 1)
       */
      minBalance?: number;
      /** @description Optional address prefix filter */
      prefix?: string;
    };
    GetAddressesWithBalanceParams: components['schemas']['GetAddressesWithBalanceParamsInner'][];
    GetNotesRequest: {
      /** @constant */
      jsonrpc: '2.0';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      method: 'getNotes';
      id: string | number | null;
      params: components['schemas']['GetNotesParams'];
    };
    GetNotesParams: components['schemas']['AddressParam'][];
    NotesResponse: {
      nicks: Record<string, never>;
      notes?: components['schemas']['NoteObject'][];
      multisig?: components['schemas']['NoteObject'][];
    };
    PaginationParam: {
      /** @description Maximum number of transactions to return */
      limit?: number;
      /** @description Number of transactions to skip (for pagination) */
      offset?: number;
    };
    EmptyParams: unknown[];
    /**
     * @description Base58-encoded block hash
     * @example 2c8Ltbg44dPkEGcNPupcVAtDgD87753M9pG2fg8yC2mTEqg5qAFvvbT
     */
    BlockHash: string;
    /**
     * @description Natural number representing block height
     * @example 12345
     */
    BlockHeight: number;
    /**
     * @description Natural number representing Unix epoch time
     * @example 1753285981
     */
    Timestamp: Record<string, never>;
    /**
     * @description Base58-encoded transaction ID
     * @example 2c8Ltbg44dPkEGcNPupcVAtDgD87753M9pG2fg8yC2mTEqg5qAFvvbT
     */
    TransactionId: string;
    /** @description Whole signed transaction serialized and Base58-encoded */
    RawTransactionBase58: string;
    /**
     * @description Base58-encoded identifier used in Nockchain
     * @example 2c8Ltbg44dPkEGcNPupcVAtDgD87753M9pG2fg8yC2mTEqg5qAFvvbT
     */
    Base58Id: string;
    /**
     * @description Base58-encoded Schnorr public key address (132 characters)
     * @example 32KVTmv3ofSyACq9nC1Hgnk4Jt8rs2hj1cvDZWC1EQuiYFMDg8MaLtF3ntafJbEUH5XPV1pK3K4xkxfjRPAWprBb7LYCVv4HF7817Bwh9M9xAdmgrPt77j4xejihNFd9h5Eo
     */
    Base58Address: string;
    CoinbaseRecipient: {
      address: components['schemas']['Base58Address'];
      /**
       * Format: int64
       * @description Amount of nicks (cryptocurrency units) awarded to this address
       */
      nicks: number;
    };
    /**
     * @description Base58-encoded hash (5-tuple format)
     * @example 2c8Ltbg44dPkEGcNPupcVAtDgD87753M9pG2fg8yC2mTEqg5qAFvvbT
     */
    NockchainHash: string;
    NoteName: {
      /** @description First hash component of the note name (note_commit) */
      firstName: components['schemas']['NockchainHash'];
      /** @description Second hash component of the note name (note_source) */
      lastName: components['schemas']['NockchainHash'];
    };
    Lock: {
      /**
       * Format: int32
       * @description Number of signatures required (m-of-n multisig)
       */
      m: number;
      /** @description Array of base58-encoded Schnorr public keys */
      pubkeys: string[];
    };
    Seed: {
      /** @description Lock that controls the recipient note */
      recipient: components['schemas']['Lock'];
      /**
       * Format: int64
       * @description Amount of assets (coins) transferred
       */
      gift: number;
      /** @description Hash of the parent note */
      parentHash: components['schemas']['NockchainHash'];
      /** @description Optional timelock constraints */
      timelockIntent: components['schemas']['Timelocks'];
      /** @description Hash of source note or block plus coinbase bool */
      outputSource: components['schemas']['OutputSource'];
    };
    Signature: {
      /** @description Base58 pubkey used to sign the challenge */
      pubkey: components['schemas']['Base58Id'];
      /** @description 8 u64 values as strings */
      chal: string[];
      /** @description 8 u64 values as strings */
      sig: string[];
    };
    Note: {
      /**
       * Format: int32
       * @description Note version number
       */
      version: number;
      /**
       * Format: int32
       * @description Block height where note was created
       */
      originPage: number;
      /** @description Optional timelock constraints */
      timelock?: components['schemas']['Timelocks'];
      /** @description Unique note identifier */
      name: components['schemas']['NoteName'];
      /** @description Lock controlling spending of this note */
      lock: components['schemas']['Lock'];
      /** @description Hash of the source (previous notes or block for coinbase) */
      sourceHash: components['schemas']['NockchainHash'];
      /** @description Whether this is a coinbase note */
      isCoinbase: boolean;
      /**
       * Format: int64
       * @description Amount of assets in this note
       */
      assets: number;
    };
    Spend: {
      /** @description Whether this spend has a signature */
      hasSignature: boolean;
      signatures: components['schemas']['Signature'][];
      /** @description Seeds defining where assets go */
      seeds: components['schemas']['Seed'][];
      /**
       * Format: int64
       * @description Transaction fee paid
       */
      fee: number;
    };
    BlockObject: {
      /**
       * @description Block hash as base58 string
       * @example 2c8Ltbg44dPkEGcNPupcVAtDgD87753M9pG2fg8yC2mTEqg5qAFvvbT
       */
      hash: string;
      /** @description Block height in the chain */
      height: number;
      /**
       * Format: unix-time
       * @description Block timestamp as seconds since Unix epoch UTC
       */
      timestamp: number;
      /** @description List of transaction IDs included in this block */
      transactions: string[];
      /**
       * @description Human-readable difficulty expression
       * @example 2^123.4
       */
      difficulty: string;
      /**
       * Format: double
       * @description Difficulty as a floating-point exponent
       * @example 123.456789
       */
      difficultyExp: number;
      /**
       * Format: double
       * @description Effective proof rate observed for this block
       */
      proofsPerSecond: number;
      /** @description Parent block hash as base58 */
      parent: string;
      /** @description Bigint mining target for this block as a string */
      target: string;
      /** @description List of coinbase recipients and their awarded amounts */
      coinbase: components['schemas']['CoinbaseRecipient'][];
      /**
       * Format: int64
       * @description Counter within the current mining epoch
       */
      epochCounter?: number | null;
      /**
       * Format: int64
       * @description Total accumulated proof-of-work up to this block
       */
      accumulatedWork?: number | null;
      /** @description Optional message included in the block */
      msg?: string | null;
      /** @description Number of transactions in this block */
      transactionCount?: number | null;
      /** @description Total size of the block in bytes */
      blockSize?: number | null;
      /**
       * Format: int64
       * @description Total transaction fees in this block
       */
      totalFees?: number | null;
    };
    TransactionObject: {
      id: components['schemas']['Base58Id'];
      inputs: components['schemas']['TransactionInput'][];
      outputs: components['schemas']['TransactionOutput'][];
      /**
       * Format: int64
       * @description Total fees in smallest unit (atoms)
       */
      totalFees: number;
      /**
       * Format: int64
       * @description Transaction size in bytes
       */
      totalSize: number;
      /** @description Combined timelock range from all inputs */
      timelocks?: components['schemas']['Timelocks'];
    };
    TransactionsResponse: {
      /** @description Array of transactions with block information */
      transactions: components['schemas']['TransactionWithBlockInfo'][];
      /** @description Total number of transactions available */
      totalCount: number;
      /** @description Pagination information (present when using limit/offset) */
      pagination?: components['schemas']['PaginationInfo'];
    };
    TransactionWithBlockInfo: {
      /** @description Transaction ID */
      txId: components['schemas']['Base58Id'];
      /** @description Block ID containing this transaction */
      blockId: components['schemas']['Base58Id'];
      /** @description Block ID containing this transaction */
      blockHeight?: components['schemas']['BlockHeight'];
      /** @description Timestamp of block containing this transaction */
      timestamp?: components['schemas']['Timestamp'];
      /** @description The transaction details */
      transaction: components['schemas']['TransactionObject'];
    };
    TransactionInput: {
      /** @description The note being spent */
      note: components['schemas']['Note'];
      /** @description The spend authorization */
      spend: components['schemas']['Spend'];
    };
    TransactionOutput: {
      /** @description The output note being created */
      note: components['schemas']['Note'];
      /** @description Seeds that created this output */
      seeds: components['schemas']['Seed'][];
    };
    AddressBalanceItem: {
      address: components['schemas']['Base58Address'];
      /** Format: int64 */
      balance: number;
      /**
       * Format: int64
       * @description Number of notes contributing to this balance
       */
      notes?: number;
    };
    BlocksRangeResponse: {
      /** @description Total number of blocks returned */
      totalBlocks: number;
      /** @description Starting block height (inclusive) */
      startHeight: number;
      /** @description Ending block height (inclusive) */
      endHeight: number;
      /**
       * Format: unix-time
       * @description Earliest timestamp in the range
       */
      minTimestamp?: number | null;
      /**
       * Format: unix-time
       * @description Latest timestamp in the range
       */
      maxTimestamp?: number | null;
      /** @description Array of blocks in the requested range */
      blocks: components['schemas']['BlockObject'][];
      /** @description Optional metadata about the query */
      metadata?: {
        /** @description Whether results were served from cache */
        cached?: boolean;
        /** @description Query execution time in milliseconds */
        queryTimeMs?: number;
      } | null;
      /**
       * Format: double
       * @description Average block time in seconds (last 144 blocks)
       */
      avgBlockTime?: number;
      /** @description Proof rate history over recent blocks */
      proofRateOverTime?: {
        height?: number;
        /** Format: double */
        proofRate?: number;
        timestamp?: number;
      }[];
      /**
       * Format: double
       * @description Seconds since last block
       */
      timeSinceLastBlock?: number;
      epochInfo?: {
        /** @description Current difficulty epoch (height / 2016) */
        currentEpoch: number;
        /** @description Blocks processed in current epoch */
        blocksInEpoch: number;
        /**
         * Format: double
         * @description Average block time for current 2016 block epoch
         */
        avgBlockTimeThisEpoch: number;
      };
      difficultyAdjustment?: {
        /** @description Blocks remaining until next difficulty adjustment */
        blocksToAdjustment: number;
        /**
         * Format: double
         * @description Estimated seconds until difficulty adjustment
         */
        estimatedTimeToAdjustment: number;
        /**
         * Format: double
         * @description Estimated next difficulty multiplier
         */
        estimatedNextDifficulty: number;
      };
      halvingInfo?: {
        /** @description Blocks remaining until next reward halving */
        blocksToHalving: number;
        /**
         * Format: double
         * @description Estimated seconds until halving
         */
        estimatedTimeToHalving: number;
        /**
         * Format: int64
         * @description Current block reward in smallest units
         */
        currentBlockReward: number;
      };
    };
    AddressTransactionsResponse: {
      /** @description The queried address */
      address: components['schemas']['Base58Address'];
      /** @description Total number of transactions for this address */
      totalTransactions: number;
      /**
       * Format: int64
       * @description Total amount received by this address (in nicks)
       */
      totalReceived?: number;
      /**
       * Format: int64
       * @description Total amount sent from this address (in nicks)
       */
      totalSent?: number;
      /**
       * Format: int64
       * @description Current balance (totalReceived - totalSent)
       */
      currentBalance?: number;
      /** @description Array of transactions involving this address */
      transactions: components['schemas']['AddressTransaction'][];
      pagination?: components['schemas']['PaginationInfo'];
      networkProofrate?: {
        /**
         * Format: double
         * @description Current network proof rate (proofs/second)
         */
        current: number;
        /**
         * Format: double
         * @description 24h average proof rate
         */
        avg24h: number;
        /**
         * Format: double
         * @description 7 day average proof rate
         */
        avg7d: number;
      };
      mempool?: {
        /** @description Number of unconfirmed transactions */
        count: number;
        /**
         * Format: int64
         * @description Total fees in mempool
         */
        totalFees: number;
        /**
         * Format: double
         * @description Average fee rate (fees per byte)
         */
        avgFeeRate: number;
      };
      feeMetrics?: {
        lastBlock: {
          /** Format: int64 */
          totalFees?: number;
          /** Format: double */
          avgFeeRate?: number;
          txCount?: number;
        };
        recommended: {
          /**
           * Format: double
           * @description Fee rate for confirmation in ~1 hour
           */
          slow?: number;
          /**
           * Format: double
           * @description Fee rate for confirmation in ~30 min
           */
          medium?: number;
          /**
           * Format: double
           * @description Fee rate for confirmation in ~10 min
           */
          fast?: number;
        };
      };
    };
    ProofRateHistoryResponse: {
      data: components['schemas']['ProofRateDataPoint'][];
    };
    ProofRateDataPoint: {
      height: number;
      /** Format: double */
      proofrate: number;
      /** Format: int64 */
      timestamp: number;
      timeDelta?: number | null;
      /** Format: double */
      difficultyAdjustment?: number | null;
    };
    AddressTransaction: {
      /** @description Transaction ID */
      txId: components['schemas']['Base58Id'];
      blockHeight: components['schemas']['BlockHeight'];
      /** @description Block hash containing this transaction */
      blockHash: components['schemas']['Base58Id'];
      /**
       * Format: unix-time
       * @description Transaction timestamp
       */
      timestamp: number;
      /**
       * @description Transaction type from address perspective
       * @enum {string}
       */
      type: 'received' | 'sent' | 'self';
      /**
       * Format: int64
       * @description Amount transferred (in nicks)
       */
      amount: number;
      /**
       * Format: int64
       * @description Transaction fee (in nicks)
       */
      fee: number;
      /** @description Transaction inputs */
      inputs?: components['schemas']['TransactionInput'][];
      /** @description Transaction outputs */
      outputs?: components['schemas']['TransactionOutput'][];
      /** @description Optional transaction note/memo */
      note?: string | null;
      /** @description All counterparty addresses in this transaction */
      counterparties?: components['schemas']['Base58Address'][] | null;
    };
    PaginationInfo: {
      limit: number;
      offset: number;
      /** @description Whether there are more items available */
      hasMore: boolean;
    };
    TipObject: {
      /** @description Tip block hash as base58 */
      hash: string;
      /** @description Tip block height */
      height: number;
    };
    HeightObject: number;
    RawTransactionObject: {
      id: components['schemas']['Base58Id'];
      inputs: components['schemas']['Base58Id'][];
      timelocks?: components['schemas']['Timelocks'];
      /** @description Total fees in smallest unit (atoms) */
      totalFees: number;
    };
    Timelocks: {
      absolute: components['schemas']['TimelockRange'];
      relative: components['schemas']['TimelockRange'];
    };
    TimelockRange: {
      /**
       * Format: int64
       * @description Minimum block height for spending
       */
      min?: number | null;
      /**
       * Format: int64
       * @description Maximum block height for spending
       */
      max?: number | null;
    };
    BalanceObject: {
      /** Format: int64 */
      nicks?: number;
      notes: components['schemas']['NoteObject'][];
    };
    NoteObject: {
      /**
       * Format: int32
       * @description Note version number.
       */
      version: number;
      /**
       * Format: int32
       * @description Block height where the note was created.
       */
      originPage: number;
      timelock?: components['schemas']['Timelocks'];
      name: components['schemas']['NoteName'];
      lock: components['schemas']['Lock'];
      /** @description Hash of the source (previous notes or block). */
      sourceHash: components['schemas']['NockchainHash'];
      /** @description True if the note is from a coinbase transaction. */
      isCoinbase: boolean;
      /**
       * Format: int64
       * @description Amount of assets in this note.
       */
      assets: number;
    };
    OutputSource: {
      /** @description Hash of the source (previous notes or block). */
      sourceHash: components['schemas']['NockchainHash'];
      /** @description True if the note is from a coinbase transaction. */
      isCoinbase: boolean;
    };
    MiningKey: {
      /** @description Number of signatures required (m-of-n) */
      m: number;
      /** @description List of public keys in the multisig */
      pubkeys: components['schemas']['Base58Id'][];
    };
    MiningPubkeysArray: components['schemas']['MiningKey'][];
    PageSummary: {
      digest: components['schemas']['Base58Id'];
      /** @description Block timestamp */
      timestamp: number;
      /** @description Counter within current epoch */
      epochCounter: number;
      /** @description Mining target for this block */
      target: components['schemas']['Base58Id'];
      /** @description Total accumulated work up to this block */
      accumulatedWork: components['schemas']['Base58Id'];
      /** @description Block height */
      height: number;
      /** @description Parent block hash */
      parent: components['schemas']['Base58Id'];
    };
    HeavySummaryObject: {
      /** @description List of mining public keys */
      pubkeys: components['schemas']['Base58Id'][];
      /** @description Summary of the heaviest block */
      pageSummary?: components['schemas']['PageSummary'];
    };
    DecentralizationMetricsResponse: {
      /** @description Starting block height of analysis */
      startHeight: number;
      /** @description Ending block height of analysis */
      endHeight: number;
      /** @description Size of each analysis window */
      windowSize: number;
      /** @description Mining decentralization metrics over time */
      miningDecentralization: components['schemas']['MiningDecentralizationWindow'][];
      /** @description Wallet growth metrics over time */
      walletGrowth: components['schemas']['WalletGrowthWindow'][];
      metadata: {
        /** @description Total number of analysis windows */
        totalWindows?: number;
        /** @description Query execution time in milliseconds */
        queryTimeMs?: number;
        /** @description Whether results were served from cache */
        cached?: boolean;
      };
    };
    NetworkHealthSummaryResponse: {
      /** @description Current blockchain height */
      currentHeight: number;
      /**
       * Format: double
       * @description Overall decentralization health score (0-100)
       */
      decentralizationScore: number;
      mining: {
        last100Blocks: components['schemas']['MiningDecentralizationWindow'];
        last1000Blocks: components['schemas']['MiningDecentralizationWindow'];
      };
      wallets: {
        last100Blocks: components['schemas']['WalletGrowthWindow'];
        last1000Blocks: components['schemas']['WalletGrowthWindow'];
      };
    };
    MiningDecentralizationResponse: {
      startHeight: number;
      endHeight: number;
      windowSize: number;
      /** @description Time series of mining decentralization metrics */
      windows: components['schemas']['MiningDecentralizationWindow'][];
    };
    WalletGrowthMetricsResponse: {
      startHeight: number;
      endHeight: number;
      windowSize: number;
      /** @description Time series of wallet growth metrics */
      windows: components['schemas']['WalletGrowthWindow'][];
    };
    MiningDecentralizationWindow: {
      /** @description Starting block height of this window */
      startHeight: number;
      /** @description Ending block height of this window */
      endHeight: number;
      /**
       * Format: unix-time
       * @description Representative timestamp for this window
       */
      timestamp: number;
      /** @description Total blocks in this window */
      totalBlocks: number;
      /** @description Number of unique miners in this window */
      uniqueMiners: number;
      /** @description Total unique miners up to this window */
      totalUniqueMiners?: number | null;
      /**
       * Format: double
       * @description Herfindahl-Hirschman Index (0=perfect competition, 1=monopoly)
       */
      herfindahlIndex: number;
      /**
       * Format: double
       * @description Share of blocks mined by top miner (0-1)
       */
      topMinerShare: number;
      /**
       * Format: double
       * @description Combined share of blocks mined by top 3 miners (0-1)
       */
      top3Share?: number;
      /**
       * Format: double
       * @description Combined share of blocks mined by top 10 miners (0-1)
       */
      top10Share?: number;
      /** @description Top miners in this window */
      miners?: components['schemas']['MinerStats'][];
      /**
       * Format: double
       * @description Average difficulty during this window
       */
      avgDifficulty?: number | null;
    };
    WalletGrowthWindow: {
      /** @description Starting block height of this window */
      startHeight: number;
      /** @description Ending block height of this window */
      endHeight: number;
      /**
       * Format: unix-time
       * @description Representative timestamp for this window
       */
      timestamp: number;
      /** @description Total unique addresses that have ever been active up to this point */
      totalUniqueAddresses: number;
      /** @description New addresses that first appeared in this window */
      newAddressesInWindow: number;
      /** @description Number of addresses with positive balance at end of window */
      activeWalletsWithBalance: number;
      /**
       * Format: double
       * @description New addresses per block in this window
       */
      growthRate?: number;
      /**
       * Format: double
       * @description Total addresses per block since genesis
       */
      cumulativeGrowthRate?: number;
    };
    MinerStats: {
      /** @description Miner's address */
      address: components['schemas']['Base58Address'];
      /**
       * Format: int32
       * @description Number of blocks mined by this miner
       */
      blocksMined: number;
      /**
       * Format: int64
       * @description Total rewards earned in nicks
       */
      totalRewards: number;
      /**
       * Format: double
       * @description Percentage of total blocks mined (0-100)
       */
      sharePercentage: number;
      /**
       * Format: int32
       * @description First block height mined by this miner
       */
      firstBlock: number;
      /**
       * Format: int32
       * @description Last block height mined by this miner
       */
      lastBlock: number;
      /**
       * Format: double
       * @description Average difficulty of blocks mined by this miner
       */
      avgDifficulty?: number | null;
    };
    AddressesWithBalanceResponse: {
      items: components['schemas']['AddressBalanceItem'][];
      totalCount: number;
      pagination?: components['schemas']['PaginationInfo'];
    };
    /** @description Simple boolean result */
    BooleanResult: boolean;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  rpc: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JsonRpcRequestEnvelope'];
      };
    };
    responses: {
      /** @description JSON-RPC success or error response */
      200: {
        headers: {
          /** @example * */
          'Access-Control-Allow-Origin'?: string;
          /** @example GET, POST, OPTIONS */
          'Access-Control-Allow-Methods'?: string;
          /** @example Content-Type, Accept, Authorization */
          'Access-Control-Allow-Headers'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonRpcResponseEnvelope'];
        };
      };
      /** @description Transport-level error (malformed JSON, wrong content-type, etc.) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransportError'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransportError'];
        };
      };
      /** @description Unexpected error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransportError'];
        };
      };
    };
  };
  rpcOptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CORS preflight response */
      200: {
        headers: {
          /** @example * */
          'Access-Control-Allow-Origin'?: string;
          /** @example GET, POST, OPTIONS */
          'Access-Control-Allow-Methods'?: string;
          /** @example Content-Type, Accept, Authorization */
          'Access-Control-Allow-Headers'?: string;
          /** @example 86400 */
          'Access-Control-Max-Age'?: number;
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
}
