// Replays the golden postcard fixtures generated by
// crates/nockster-core/tests/protocol_fixtures.rs (see that file for the
// regeneration workflow). Requests/frames are serialized here and compared
// byte-for-byte against the Rust encoding; responses are Rust-encoded bytes
// that must deserialize correctly here. A failure means protocol.ts and
// nockster-core disagree about the wire format.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { serializeMsg, deserializeMsg } from '../dist/index.js';

const FIXTURES_PATH = fileURLToPath(
  new URL('./fixtures/protocol-fixtures.txt', import.meta.url),
);

const PROTO_V1 = 1;
const FIXTURE_MSG_ID = 777;

function parseFixtures() {
  const fixtures = [];
  for (const line of readFileSync(FIXTURES_PATH, 'utf8').split('\n')) {
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    assert.notEqual(eq, -1, `malformed fixture line: ${line}`);
    fixtures.push({ name: line.slice(0, eq), hex: line.slice(eq + 1) });
  }
  assert.ok(fixtures.length > 0, 'no fixtures parsed');
  return fixtures;
}

function toHex(bytes) {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

function fromHex(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

const filled = (len, value) => new Uint8Array(len).fill(value);
const counting = (len) => Uint8Array.from({ length: len }, (_, i) => i);

const manifest = () => ({
  manifest_version: 1,
  release_version: 42,
  image_size: 1024,
  image_sha256: filled(32, 0xaa),
  signing_pubkey_sha256: filled(32, 0xbb),
  hardware_target: 'esp32s3',
  build_profile: 'dev',
  protocol_v: 1,
  git_commit: 'abc123',
  tx_types_rev: 'def456',
});

const spendMeta = () => ({
  outputs: [{ gift: 1000n, recipient_pkh_b58: 'addr1', is_refund: false }],
});

// One builder per `req:` fixture, mirroring the values in the Rust test.
const requestBuilders = {
  Hello: { type: 'Hello' },
  GetInfo: { type: 'GetInfo' },
  Ping: { type: 'Ping' },
  Wipe: { type: 'Wipe' },
  SetSeed: { type: 'SetSeed', seed64: filled(64, 0x11) },
  GetFingerprint: { type: 'GetFingerprint' },
  GetPubkey: { type: 'GetPubkey', path: [44, 0, 7], compressed: true },
  GetXpub: { type: 'GetXpub', path: [44, 1] },
  SignDigest: { type: 'SignDigest', path: [2147483692], digest32: counting(32) },
  GetCheetahPub: { type: 'GetCheetahPub', slot: 2, path: [44, 0] },
  'SignSpendHash#meta': {
    type: 'SignSpendHash',
    slot: 1,
    path: [44],
    msg5: [1n, 2n, 0xffffffffffffffffn, 4n, 5n],
    meta: spendMeta(),
  },
  'SignSpendHash#nometa': {
    type: 'SignSpendHash',
    slot: 1,
    path: [44],
    msg5: [1n, 2n, 3n, 4n, 5n],
  },
  SignSpendHashFor: {
    type: 'SignSpendHashFor',
    slot: 0,
    path: [44, 9],
    msg5: [9n, 8n, 7n, 6n, 5n],
    pubkey: { x: [1n, 2n, 3n, 4n, 5n, 6n], y: [7n, 8n, 9n, 10n, 11n, 12n] },
  },
  Health: { type: 'Health' },
  InitializePIN: { type: 'InitializePIN', pin: '1234', seed64: filled(64, 0x22) },
  AddSeed: { type: 'AddSeed', seed64: filled(64, 0x33) },
  DeleteSeed: { type: 'DeleteSeed', slot: 3 },
  Unlock: { type: 'Unlock', pin: '1234' },
  Lock: { type: 'Lock' },
  ResetPIN: { type: 'ResetPIN', current_pin: '1234', new_pin: '5678' },
  GetLockStatus: { type: 'GetLockStatus' },
  SelectSeed: { type: 'SelectSeed', slot: 1 },
  Reset: { type: 'Reset' },
  GetSecurityStatus: { type: 'GetSecurityStatus' },
  GetBuildInfo: { type: 'GetBuildInfo' },
  GetTouchCalibration: { type: 'GetTouchCalibration' },
  SetTouchCalibration: {
    type: 'SetTouchCalibration',
    calibration: {
      raw_x_min: 1,
      raw_x_max: 4000,
      raw_y_min: 3,
      raw_y_max: 4001,
      mirror_x: true,
      mirror_y: false,
    },
  },
  ShowTouchDiagnostics: { type: 'ShowTouchDiagnostics', enabled: true },
  GetSeedLabels: { type: 'GetSeedLabels' },
  SetSeedLabel: { type: 'SetSeedLabel', slot: 0, label: 'main' },
  ChangePinOnDevice: { type: 'ChangePinOnDevice', current_pin: '1234' },
  StartTouchCalibration: { type: 'StartTouchCalibration' },
  GetUpdateTrust: { type: 'GetUpdateTrust' },
  VerifyUpdateManifest: {
    type: 'VerifyUpdateManifest',
    manifest: manifest(),
    signature64: filled(64, 0x44),
    signing_pubkey_sec1: filled(33, 0x02),
  },
  BeginUpdate: {
    type: 'BeginUpdate',
    manifest: manifest(),
    signature64: filled(64, 0x44),
    signing_pubkey_sec1: filled(33, 0x02),
    write_flash: true,
  },
  UpdateChunk: { type: 'UpdateChunk', offset: 512, chunk: filled(8, 0xab) },
  FinishUpdate: { type: 'FinishUpdate' },
  CancelUpdate: { type: 'CancelUpdate' },
  GetUpdateStatus: { type: 'GetUpdateStatus' },
  GetReleaseInfo: { type: 'GetReleaseInfo' },
  GetUpdateBootStatus: { type: 'GetUpdateBootStatus' },
  Reboot: { type: 'Reboot' },
  GetAddressBook: { type: 'GetAddressBook' },
  VaultStore: { type: 'VaultStore', label: 'htlc-1', preimage: filled(24, 0x5a) },
  VaultList: { type: 'VaultList' },
  VaultReveal: { type: 'VaultReveal', slot: 2 },
  VaultDelete: { type: 'VaultDelete', slot: 2 },
  GetMasterPubkey: { type: 'GetMasterPubkey', slot: 0 },
};

const frameBuilders = {
  FragBegin: { type: 'FragBegin', id: 5, total_len: 1024, kind: 'SignDraft' },
  FragPart: { type: 'FragPart', id: 5, offset: 512, chunk: filled(4, 0xcd), last: true },
};

// One validator per `resp:` fixture.
const responseValidators = {
  Hello: (m) => {
    assert.equal(m.proto_v, 1);
    assert.equal(m.compressed_pk, false);
  },
  FragBegin: (m) => {
    assert.equal(m.id, 9);
    assert.equal(m.total_len, 2048);
    assert.equal(m.kind, 'SignDraft');
  },
  FragPart: (m) => {
    assert.equal(m.id, 9);
    assert.equal(m.offset, 0);
    assert.equal(toHex(m.chunk), 'efefefef');
    assert.equal(m.last, false);
  },
  Info: (m) => {
    assert.equal(m.proto_v, 1);
    assert.equal(m.fw_major, 0);
    assert.equal(m.fw_minor, 1);
    assert.equal(m.features, 0x3fff);
    assert.equal(m.has_seed, true);
    assert.equal(m.cheetah_pubs.length, 1);
    assert.deepEqual(m.cheetah_pubs[0].path, [44, 0]);
  },
  Pong: () => {},
  Ok: () => {},
  OkSig: (m) => assert.equal(toHex(m.sig64), '55'.repeat(64)),
  OkFingerprint: (m) => assert.equal(toHex(m.fp4), '01020304'),
  OkPubkey: (m) => assert.equal(toHex(m.uncompressed), '04'.repeat(65)),
  OkPubkeyCompressed: (m) => assert.equal(toHex(m.compressed), '03'.repeat(33)),
  OkXpub: (m) => {
    assert.equal(m.xpub.depth, 1);
    assert.equal(m.xpub.child, 5);
    assert.equal(toHex(m.xpub.chain_code), '10'.repeat(32));
  },
  OkCheetahPub: (m) => {
    assert.equal(m.x[5], 0xffffffffffffffffn);
    assert.equal(m.y[0], 7n);
  },
  OkCheetahSig: (m) => {
    assert.equal(m.chal[0], 1n);
    assert.equal(m.sig[7], 16n);
  },
  OkLockStatus: (m) => {
    assert.equal(m.locked, true);
    assert.equal(m.attempts_remaining, 7);
  },
  Err: (m) => assert.equal(m.code, 0x0103),
  OkSecurityStatus: (m) => {
    assert.equal(m.status.chip_security_available, true);
    assert.equal(toHex(m.status.mac), '010203040506');
    assert.equal(m.status.nvs_schema_version, 2);
    assert.equal(m.status.nvs_slot_count, 1);
  },
  OkBuildInfo: (m) => {
    assert.equal(m.info.git_commit, 'abc123');
    assert.equal(m.info.build_profile, 'dev');
    assert.equal(m.info.tx_types_rev, 'def456');
  },
  OkTouchCalibration: (m) => {
    assert.equal(m.calibration.raw_x_max, 4000);
    assert.equal(m.calibration.mirror_x, false);
    assert.equal(m.calibration.mirror_y, true);
  },
  OkSeedLabels: (m) => {
    assert.equal(m.labels.length, 1);
    assert.equal(m.labels[0].slot, 0);
    assert.equal(m.labels[0].label, 'main');
  },
  OkUpdateTrust: (m) => {
    assert.equal(m.trust.configured, true);
    assert.equal(toHex(m.trust.pubkey_sha256), 'bb'.repeat(32));
  },
  OkUpdateStatus: (m) => {
    assert.equal(m.status.active, true);
    assert.equal(m.status.bytes_received, 4096);
    assert.equal(m.status.image_size, 1024);
  },
  OkReleaseInfo: (m) => assert.equal(m.info.release_version, 42),
  OkUpdateBootStatus: (m) => {
    assert.equal(m.status.partition_table_ok, true);
    assert.equal(m.status.ota0_offset, 0x320000);
    assert.equal(m.status.ota1_size, 0x300000);
  },
  OkAddressBook: (m) => {
    assert.equal(m.entries.length, 1);
    assert.equal(m.entries[0].label, 'alice');
    assert.equal(m.entries[0].pkh, 'addr1');
  },
  OkVaultEntries: (m) => {
    assert.equal(m.entries.length, 1);
    assert.equal(m.entries[0].slot, 2);
    assert.equal(m.entries[0].commitment[4], 0xffffffffffffffffn);
    assert.equal(m.entries[0].label, 'htlc-1');
    assert.equal(m.entries[0].preimage_len, 24);
  },
  OkVaultPreimage: (m) => {
    assert.equal(m.commitment[0], 1n);
    assert.equal(toHex(m.preimage), '5a'.repeat(24));
  },
  OkMasterPubkey: (m) => {
    assert.equal(m.x[0], 1n);
    assert.equal(m.y[5], 0xffffffffffffffffn);
    assert.equal(toHex(m.chain_code), '42'.repeat(32));
  },
};

const fixtures = parseFixtures();

test('every golden fixture is covered and every builder/validator is exercised', () => {
  const seen = new Set(fixtures.map((f) => f.name));
  for (const name of Object.keys(requestBuilders)) {
    assert.ok(seen.has(`req:${name}`), `builder req:${name} has no fixture; regenerate the golden file`);
  }
  for (const name of Object.keys(frameBuilders)) {
    assert.ok(seen.has(`frame:${name}`), `builder frame:${name} has no fixture`);
  }
  for (const name of Object.keys(responseValidators)) {
    assert.ok(seen.has(`resp:${name}`), `validator resp:${name} has no fixture`);
  }
  for (const { name } of fixtures) {
    const [kind, variant] = name.split(':');
    const table =
      kind === 'req' ? requestBuilders : kind === 'frame' ? frameBuilders : responseValidators;
    assert.ok(
      Object.hasOwn(table, variant),
      `fixture ${name} has no ${kind === 'resp' ? 'validator' : 'builder'} in this test; ` +
        'a protocol variant was added in Rust — update protocol.ts and this test',
    );
  }
});

for (const { name, hex } of fixtures.filter((f) => f.name.startsWith('req:'))) {
  const variant = name.slice('req:'.length);
  test(`request fixture ${variant} serializes identically to Rust`, () => {
    const request = requestBuilders[variant];
    assert.ok(request, `no builder for ${name}`);
    const bytes = serializeMsg({
      v: PROTO_V1,
      id: FIXTURE_MSG_ID,
      msg: { type: 'One', request },
    });
    assert.equal(toHex(bytes), hex, `wire bytes for ${name} diverge from nockster-core`);
  });
}

for (const { name, hex } of fixtures.filter((f) => f.name.startsWith('frame:'))) {
  const variant = name.slice('frame:'.length);
  test(`frame fixture ${variant} serializes identically to Rust`, () => {
    const frame = frameBuilders[variant];
    assert.ok(frame, `no builder for ${name}`);
    const bytes = serializeMsg({ v: PROTO_V1, id: FIXTURE_MSG_ID, msg: frame });
    assert.equal(toHex(bytes), hex, `wire bytes for ${name} diverge from nockster-core`);
  });
}

for (const { name, hex } of fixtures.filter((f) => f.name.startsWith('resp:'))) {
  const variant = name.slice('resp:'.length);
  test(`response fixture ${variant} deserializes from Rust bytes`, () => {
    const validator = responseValidators[variant];
    assert.ok(validator, `no validator for ${name}`);
    const msg = deserializeMsg(fromHex(hex));
    assert.equal(msg.v, PROTO_V1);
    assert.equal(msg.id, FIXTURE_MSG_ID);
    assert.equal(msg.msg.type, variant, `decoded wrong variant for ${name}`);
    validator(msg.msg);
  });
}
