/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockObjectV1 {
    /// Block version number
    
    #[serde(rename = "version")]
    pub version: i32,
    /// Block hash/digest as base58 string
    
    #[serde(rename = "digest")]
    pub digest: String,
    /// URL to the proof for this block
    
    #[serde(rename = "proofUrl")]
    pub proof_url: String,
    /// Parent block hash as base58 string
    
    #[serde(rename = "parent")]
    pub parent: String,
    /// Array of transaction IDs (base58)
    
    #[serde(rename = "txids")]
    pub txids: Vec<String>,
    /// Array of coinbase note objects
    
    #[serde(rename = "coinbaseNotes")]
    pub coinbase_notes: Vec<models::NoteObjectV1>,
    /// Block timestamp in Unix seconds
    
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    /// Counter within the current epoch
    
    #[serde(rename = "epochCounter")]
    pub epoch_counter: i64,
    /// Total accumulated work as string
    
    #[serde(rename = "accumulatedWork")]
    pub accumulated_work: String,
    /// Mining target as string
    
    #[serde(rename = "target")]
    pub target: String,
    /// Block height in the chain
    
    #[serde(rename = "height")]
    pub height: i64,
    /// Optional message included in the block
    
    #[serde(rename = "msg")]
    pub msg: String,
    /// Optional array of full transaction objects (only if includeTransactions was true)
    
    #[serde(rename = "transactionsData", skip_serializing_if = "Option::is_none")]
    pub transactions_data: Option<Vec<models::TransactionObjectV1>>,
}

impl BlockObjectV1 {
    pub fn new(version: i32, digest: String, proof_url: String, parent: String, txids: Vec<String>, coinbase_notes: Vec<models::NoteObjectV1>, timestamp: i64, epoch_counter: i64, accumulated_work: String, target: String, height: i64, msg: String) -> BlockObjectV1 {
        BlockObjectV1 {
            version,
            digest,
            proof_url,
            parent,
            txids,
            coinbase_notes,
            timestamp,
            epoch_counter,
            accumulated_work,
            target,
            height,
            msg,
            transactions_data: None,
        }
    }
}

