/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlocksByHeightParams {
    /// Array of block heights to query
    
    #[serde(rename = "heights")]
    pub heights: Vec<i32>,
    /// Whether to include full transaction data
    
    #[serde(rename = "includeTransactions", skip_serializing_if = "Option::is_none")]
    pub include_transactions: Option<bool>,
}

impl GetBlocksByHeightParams {
    pub fn new(heights: Vec<i32>) -> GetBlocksByHeightParams {
        GetBlocksByHeightParams {
            heights,
            include_transactions: None,
        }
    }
}

