/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNotesInAssetRangeParams {
    /// Minimum asset amount
    
    #[serde(rename = "minAsset")]
    pub min_asset: i64,
    /// Maximum asset amount
    
    #[serde(rename = "maxAsset")]
    pub max_asset: i64,
    /// Whether to include spent notes
    
    #[serde(rename = "showSpent", skip_serializing_if = "Option::is_none")]
    pub show_spent: Option<bool>,
}

impl GetNotesInAssetRangeParams {
    pub fn new(min_asset: i64, max_asset: i64) -> GetNotesInAssetRangeParams {
        GetNotesInAssetRangeParams {
            min_asset,
            max_asset,
            show_spent: None,
        }
    }
}

