/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNotesFromBlocksParams {
    /// Array of block IDs (base58)
    
    #[serde(rename = "blockIds")]
    pub block_ids: Vec<String>,
    /// Whether to include spent notes
    
    #[serde(rename = "showSpent", skip_serializing_if = "Option::is_none")]
    pub show_spent: Option<bool>,
}

impl GetNotesFromBlocksParams {
    pub fn new(block_ids: Vec<String>) -> GetNotesFromBlocksParams {
        GetNotesFromBlocksParams {
            block_ids,
            show_spent: None,
        }
    }
}

