/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTipRequest {
    
    #[serde(rename = "jsonrpc")]
    pub jsonrpc: Jsonrpc,
    
    #[serde(rename = "method")]
    pub method: Method,
    
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<Box<models::GetBlocksByHeightRequestId>>,
    
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<models::GetTipParams>>,
}

impl GetTipRequest {
    pub fn new(jsonrpc: Jsonrpc, method: Method, id: Option<models::GetBlocksByHeightRequestId>) -> GetTipRequest {
        GetTipRequest {
            jsonrpc,
            method,
            id: if let Some(x) = id {Some(Box::new(x))} else {None},
            params: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Jsonrpc {
    #[serde(rename = "2.0")]
    Variant2Period0,
}

impl Default for Jsonrpc {
    fn default() -> Jsonrpc {
        Self::Variant2Period0
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "getTip")]
    GetTip,
}

impl Default for Method {
    fn default() -> Method {
        Self::GetTip
    }
}

