/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsonRpcResponseEnvelope : Standard JSON-RPC 2.0 response. Exactly **one** of `result` or `error` MUST appear. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonRpcResponseEnvelope {
    
    #[serde(rename = "jsonrpc")]
    pub jsonrpc: Jsonrpc,
    
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::JsonRpcResponseEnvelopeResult>>,
    
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::JsonRpcError>>,
    
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<Box<models::JsonRpcResponseEnvelopeId>>,
}

impl JsonRpcResponseEnvelope {
    /// Standard JSON-RPC 2.0 response. Exactly **one** of `result` or `error` MUST appear. 
    pub fn new(jsonrpc: Jsonrpc, id: Option<models::JsonRpcResponseEnvelopeId>) -> JsonRpcResponseEnvelope {
        JsonRpcResponseEnvelope {
            jsonrpc,
            result: None,
            error: None,
            id: if let Some(x) = id {Some(Box::new(x))} else {None},
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Jsonrpc {
    #[serde(rename = "2.0")]
    Variant2Period0,
}

impl Default for Jsonrpc {
    fn default() -> Jsonrpc {
        Self::Variant2Period0
    }
}

