/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcRequestEnvelope {
    #[serde(rename="getBlocksByHeight")]
    GetBlocksByHeight(Box<models::GetBlocksByHeightRequest>),
    #[serde(rename="getBlocksById")]
    GetBlocksById(Box<models::GetBlocksByIdRequest>),
    #[serde(rename="getBlockIdsByHeight")]
    GetBlockIdsByHeight(Box<models::GetBlockIdsByHeightRequest>),
    #[serde(rename="getBlocksByTimestampRange")]
    GetBlocksByTimestampRange(Box<models::GetBlocksByTimestampRangeRequest>),
    #[serde(rename="getTip")]
    GetTip(Box<models::GetTipRequest>),
    #[serde(rename="getNotesByAddress")]
    GetNotesByAddress(Box<models::GetNotesByAddressRequest>),
    #[serde(rename="getNotesByFirstName")]
    GetNotesByFirstName(Box<models::GetNotesByFirstNameRequest>),
    #[serde(rename="getNotesFromBlocks")]
    GetNotesFromBlocks(Box<models::GetNotesFromBlocksRequest>),
    #[serde(rename="getNotesInAssetRange")]
    GetNotesInAssetRange(Box<models::GetNotesInAssetRangeRequest>),
    #[serde(rename="getTransactionsByAddress")]
    GetTransactionsByAddress(Box<models::GetTransactionsByAddressRequest>),
    #[serde(rename="getTransactionsByBlockId")]
    GetTransactionsByBlockId(Box<models::GetTransactionsByBlockIdRequest>),
    #[serde(rename="getTransactionsByBlockHeight")]
    GetTransactionsByBlockHeight(Box<models::GetTransactionsByBlockHeightRequest>),
    #[serde(rename="getTransactionByTxid")]
    GetTransactionByTxid(Box<models::GetTransactionByTxidRequest>),
}

impl Default for JsonRpcRequestEnvelope {
    fn default() -> Self {
        Self::GetBlocksByHeight(Default::default())
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Jsonrpc {
    #[serde(rename = "2.0")]
    Variant2Period0,
}

impl Default for Jsonrpc {
    fn default() -> Jsonrpc {
        Self::Variant2Period0
    }
}

