/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LockObject {
    /// Number of signatures required
    
    #[serde(rename = "m")]
    pub m: i32,
    /// Array of public keys (base58)
    
    #[serde(rename = "pubkeys")]
    pub pubkeys: Vec<String>,
}

impl LockObject {
    pub fn new(m: i32, pubkeys: Vec<String>) -> LockObject {
        LockObject {
            m,
            pubkeys,
        }
    }
}

