/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LockPrimitiveObject : Lock primitive - exactly one property should be present
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LockPrimitiveObject {
    
    #[serde(rename = "pkh", skip_serializing_if = "Option::is_none")]
    pub pkh: Option<Box<models::LockPrimitiveObjectPkh>>,
    
    #[serde(rename = "tim", skip_serializing_if = "Option::is_none")]
    pub tim: Option<Box<models::LockPrimitiveObjectTim>>,
    
    #[serde(rename = "hax", skip_serializing_if = "Option::is_none")]
    pub hax: Option<Vec<String>>,
    
    #[serde(rename = "brn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brn: Option<Option<serde_json::Value>>,
}

impl LockPrimitiveObject {
    /// Lock primitive - exactly one property should be present
    pub fn new() -> LockPrimitiveObject {
        LockPrimitiveObject {
            pkh: None,
            tim: None,
            hax: None,
            brn: None,
        }
    }
}

