/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LockMerkleProofObject {
    
    #[serde(rename = "spendCondition")]
    pub spend_condition: Vec<models::LockPrimitiveObject>,
    
    #[serde(rename = "axis")]
    pub axis: i64,
    /// Merkle root (base58)
    
    #[serde(rename = "merkleProofRoot")]
    pub merkle_proof_root: String,
    /// Merkle path (array of base58 strings)
    
    #[serde(rename = "merkleProofPath")]
    pub merkle_proof_path: Vec<String>,
}

impl LockMerkleProofObject {
    pub fn new(spend_condition: Vec<models::LockPrimitiveObject>, axis: i64, merkle_proof_root: String, merkle_proof_path: Vec<String>) -> LockMerkleProofObject {
        LockMerkleProofObject {
            spend_condition,
            axis,
            merkle_proof_root,
            merkle_proof_path,
        }
    }
}

