/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoteV0Object {
    /// Note version
    
    #[serde(rename = "version")]
    pub version: Version,
    /// Block height where note originated
    
    #[serde(rename = "originPage")]
    pub origin_page: i64,
    /// Block ID as base58 string
    
    #[serde(rename = "blockId")]
    pub block_id: String,
    /// Timelock constraints
    
    #[serde(rename = "timelock", skip_serializing_if = "Option::is_none")]
    pub timelock: Option<Box<models::TimelockV0>>,
    /// First component of note name (base58)
    
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// Second component of note name (base58)
    
    #[serde(rename = "lastName")]
    pub last_name: String,
    /// Lock controlling the note
    
    #[serde(rename = "lock")]
    pub lock: Box<models::LockObject>,
    /// Source hash (base58)
    
    #[serde(rename = "sourceHash")]
    pub source_hash: String,
    /// Whether this is a coinbase note
    
    #[serde(rename = "isCoinbase")]
    pub is_coinbase: bool,
    /// Amount of assets in this note
    
    #[serde(rename = "assets")]
    pub assets: i64,
    /// Transaction ID where this note was spent (null if unspent)
    
    #[serde(rename = "spentOn", skip_serializing_if = "Option::is_none")]
    pub spent_on: Option<String>,
}

impl NoteV0Object {
    pub fn new(version: Version, origin_page: i64, block_id: String, first_name: String, last_name: String, lock: models::LockObject, source_hash: String, is_coinbase: bool, assets: i64) -> NoteV0Object {
        NoteV0Object {
            version,
            origin_page,
            block_id,
            timelock: None,
            first_name,
            last_name,
            lock: Box::new(lock),
            source_hash,
            is_coinbase,
            assets,
            spent_on: None,
        }
    }
}
/// Note version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "0")]
    Variant0,
}

impl Default for Version {
    fn default() -> Version {
        Self::Variant0
    }
}

