/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NoteObjectV1 {
    #[serde(rename="0")]
    Model0(Box<models::NoteV0Object>),
    #[serde(rename="1")]
    Model1(Box<models::NoteV1Object>),
}

impl Default for NoteObjectV1 {
    fn default() -> Self {
        Self::Model0(Default::default())
    }
}


