/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoteV1Object {
    /// Note version
    
    #[serde(rename = "version")]
    pub version: Version,
    /// Block height where note originated
    
    #[serde(rename = "originPage")]
    pub origin_page: i64,
    /// First component of note name (base58)
    
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// Second component of note name (base58)
    
    #[serde(rename = "lastName")]
    pub last_name: String,
    /// Map of keys to values. Special keys are processed: - \"lock\": Object with {version: u64, data: [LockPrimitiveObject]} - Other keys: Base64-encoded bytes (string) 
    
    #[serde(rename = "noteData")]
    pub note_data: std::collections::HashMap<String, serde_json::Value>,
    /// Amount of assets in this note
    
    #[serde(rename = "assets")]
    pub assets: i64,
    /// Whether this is a coinbase note
    
    #[serde(rename = "isCoinbase")]
    pub is_coinbase: bool,
    /// Transaction ID where this note was spent (null if unspent)
    
    #[serde(rename = "spentOn", skip_serializing_if = "Option::is_none")]
    pub spent_on: Option<String>,
}

impl NoteV1Object {
    pub fn new(version: Version, origin_page: i64, first_name: String, last_name: String, note_data: std::collections::HashMap<String, serde_json::Value>, assets: i64, is_coinbase: bool) -> NoteV1Object {
        NoteV1Object {
            version,
            origin_page,
            first_name,
            last_name,
            note_data,
            assets,
            is_coinbase,
            spent_on: None,
        }
    }
}
/// Note version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "1")]
    Variant1,
}

impl Default for Version {
    fn default() -> Version {
        Self::Variant1
    }
}

