/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeedV1Object {
    /// Output hash (base58), null if no source
    
    #[serde(rename = "outputHash", skip_serializing_if = "Option::is_none")]
    pub output_hash: Option<String>,
    
    #[serde(rename = "isCoinbase")]
    pub is_coinbase: bool,
    /// Lock merkle root (base58)
    
    #[serde(rename = "lockRoot")]
    pub lock_root: String,
    /// Map of keys to values. Special keys are processed: - \"lock\": Object with {version: u64, data: [LockPrimitiveObject]} - Other keys: Base64-encoded bytes (string) 
    
    #[serde(rename = "noteData")]
    pub note_data: std::collections::HashMap<String, serde_json::Value>,
    
    #[serde(rename = "gift")]
    pub gift: i64,
    /// Parent hash (base58)
    
    #[serde(rename = "parentHash")]
    pub parent_hash: String,
}

impl SeedV1Object {
    pub fn new(is_coinbase: bool, lock_root: String, note_data: std::collections::HashMap<String, serde_json::Value>, gift: i64, parent_hash: String) -> SeedV1Object {
        SeedV1Object {
            output_hash: None,
            is_coinbase,
            lock_root,
            note_data,
            gift,
            parent_hash,
        }
    }
}

