/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeedV0Object {
    /// Output source hash (base58), null if no source
    
    #[serde(rename = "outputSourceHash", skip_serializing_if = "Option::is_none")]
    pub output_source_hash: Option<String>,
    
    #[serde(rename = "recipientLock")]
    pub recipient_lock: Box<models::LockObject>,
    
    #[serde(rename = "timelockIntent", skip_serializing_if = "Option::is_none")]
    pub timelock_intent: Option<Box<models::TimelockV0>>,
    
    #[serde(rename = "gift")]
    pub gift: i64,
    /// Parent hash (base58)
    
    #[serde(rename = "parentHash")]
    pub parent_hash: String,
}

impl SeedV0Object {
    pub fn new(recipient_lock: models::LockObject, gift: i64, parent_hash: String) -> SeedV0Object {
        SeedV0Object {
            output_source_hash: None,
            recipient_lock: Box::new(recipient_lock),
            timelock_intent: None,
            gift,
            parent_hash,
        }
    }
}

