/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignatureV0Object {
    /// Public key (base58)
    
    #[serde(rename = "pubkey")]
    pub pubkey: String,
    /// Challenge values (8 u64 as strings)
    
    #[serde(rename = "chal")]
    pub chal: Vec<String>,
    /// Signature values (8 u64 as strings)
    
    #[serde(rename = "sig")]
    pub sig: Vec<String>,
}

impl SignatureV0Object {
    pub fn new(pubkey: String, chal: Vec<String>, sig: Vec<String>) -> SignatureV0Object {
        SignatureV0Object {
            pubkey,
            chal,
            sig,
        }
    }
}

