/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendV0Object {
    
    #[serde(rename = "signature")]
    pub signature: Vec<models::SignatureV0Object>,
    
    #[serde(rename = "seeds")]
    pub seeds: Vec<models::SeedV0Object>,
    
    #[serde(rename = "fee")]
    pub fee: i64,
}

impl SpendV0Object {
    pub fn new(signature: Vec<models::SignatureV0Object>, seeds: Vec<models::SeedV0Object>, fee: i64) -> SpendV0Object {
        SpendV0Object {
            signature,
            seeds,
            fee,
        }
    }
}

