/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendV1Object {
    /// First name of spent note (base58)
    
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// Last name of spent note (base58)
    
    #[serde(rename = "lastName")]
    pub last_name: String,
    /// Spend version - v1 uses witness, v0_to_v1 uses signaturesV0
    
    #[serde(rename = "version")]
    pub version: Version,
    /// V1 witness data (only present for version=v1)
    
    #[serde(rename = "witness", skip_serializing_if = "Option::is_none")]
    pub witness: Option<Box<models::WitnessObject>>,
    /// V0 signatures (only present for version=v0_to_v1)
    
    #[serde(rename = "signaturesV0", skip_serializing_if = "Option::is_none")]
    pub signatures_v0: Option<Vec<models::SignatureV0Object>>,
    
    #[serde(rename = "seeds")]
    pub seeds: Vec<models::SeedV1Object>,
    
    #[serde(rename = "fee")]
    pub fee: i64,
}

impl SpendV1Object {
    pub fn new(first_name: String, last_name: String, version: Version, seeds: Vec<models::SeedV1Object>, fee: i64) -> SpendV1Object {
        SpendV1Object {
            first_name,
            last_name,
            version,
            witness: None,
            signatures_v0: None,
            seeds,
            fee,
        }
    }
}
/// Spend version - v1 uses witness, v0_to_v1 uses signaturesV0
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "v1")]
    V1,
    #[serde(rename = "v0_to_v1")]
    V0ToV1,
}

impl Default for Version {
    fn default() -> Version {
        Self::V1
    }
}

