/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelockV0 {
    
    #[serde(rename = "absolute")]
    pub absolute: Box<models::TimelockRange>,
    
    #[serde(rename = "relative")]
    pub relative: Box<models::TimelockRange>,
}

impl TimelockV0 {
    pub fn new(absolute: models::TimelockRange, relative: models::TimelockRange) -> TimelockV0 {
        TimelockV0 {
            absolute: Box::new(absolute),
            relative: Box::new(relative),
        }
    }
}

