/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionV0ObjectTimelockRange {
    
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<i64>,
    
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<i64>,
}

impl TransactionV0ObjectTimelockRange {
    pub fn new() -> TransactionV0ObjectTimelockRange {
        TransactionV0ObjectTimelockRange {
            min: None,
            max: None,
        }
    }
}

