/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionV1Object {
    /// Transaction version
    
    #[serde(rename = "version")]
    pub version: Version,
    /// Transaction ID (base58)
    
    #[serde(rename = "id")]
    pub id: String,
    /// Total size of transaction
    
    #[serde(rename = "totalSize")]
    pub total_size: i64,
    
    #[serde(rename = "outputs")]
    pub outputs: Vec<models::TransactionOutputV1Object>,
    
    #[serde(rename = "spends")]
    pub spends: Vec<models::SpendV1Object>,
    /// Block ID containing this transaction (base58)
    
    #[serde(rename = "blockId")]
    pub block_id: String,
}

impl TransactionV1Object {
    pub fn new(version: Version, id: String, total_size: i64, outputs: Vec<models::TransactionOutputV1Object>, spends: Vec<models::SpendV1Object>, block_id: String) -> TransactionV1Object {
        TransactionV1Object {
            version,
            id,
            total_size,
            outputs,
            spends,
            block_id,
        }
    }
}
/// Transaction version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "1")]
    Variant1,
}

impl Default for Version {
    fn default() -> Version {
        Self::Variant1
    }
}

