/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionV0Object {
    /// Transaction version
    
    #[serde(rename = "version")]
    pub version: Version,
    /// Transaction ID (base58)
    
    #[serde(rename = "id")]
    pub id: String,
    /// Total size of transaction
    
    #[serde(rename = "totalSize")]
    pub total_size: i64,
    /// Total fees paid
    
    #[serde(rename = "totalFees")]
    pub total_fees: i64,
    
    #[serde(rename = "timelockRange")]
    pub timelock_range: Box<models::TransactionV0ObjectTimelockRange>,
    
    #[serde(rename = "outputs")]
    pub outputs: Vec<models::TransactionOutputV0Object>,
    
    #[serde(rename = "inputs")]
    pub inputs: Vec<models::TransactionInputV0Object>,
    /// Block ID containing this transaction (base58)
    
    #[serde(rename = "blockId")]
    pub block_id: String,
}

impl TransactionV0Object {
    pub fn new(version: Version, id: String, total_size: i64, total_fees: i64, timelock_range: models::TransactionV0ObjectTimelockRange, outputs: Vec<models::TransactionOutputV0Object>, inputs: Vec<models::TransactionInputV0Object>, block_id: String) -> TransactionV0Object {
        TransactionV0Object {
            version,
            id,
            total_size,
            total_fees,
            timelock_range: Box::new(timelock_range),
            outputs,
            inputs,
            block_id,
        }
    }
}
/// Transaction version
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "0")]
    Variant0,
}

impl Default for Version {
    fn default() -> Version {
        Self::Variant0
    }
}

