/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionOutputV1Object {
    /// First name of output note (base58)
    
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// Last name of output note (base58)
    
    #[serde(rename = "lastName")]
    pub last_name: String,
    
    #[serde(rename = "seeds")]
    pub seeds: Vec<models::SeedV1Object>,
}

impl TransactionOutputV1Object {
    pub fn new(first_name: String, last_name: String, seeds: Vec<models::SeedV1Object>) -> TransactionOutputV1Object {
        TransactionOutputV1Object {
            first_name,
            last_name,
            seeds,
        }
    }
}

