/*
 * Nockchain JSON-RPC v1
 *
 * Streamlined RPC API for Nockchain v1. Focuses on core blockchain data types. The service implements JSON-RPC 2.0 over HTTP POST at `/rpc/v1`. All requests and responses are `application/json` with a UTF-8 body. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WitnessObject {
    
    #[serde(rename = "lockMerkleProof")]
    pub lock_merkle_proof: Box<models::LockMerkleProofObject>,
    /// Array of PKH signatures
    
    #[serde(rename = "pkhSignature")]
    pub pkh_signature: Vec<models::PkhSignatureObject>,
    /// Map of keys to base64-encoded bytes
    
    #[serde(rename = "hax")]
    pub hax: std::collections::HashMap<String, String>,
    
    #[serde(rename = "tim")]
    pub tim: i64,
}

impl WitnessObject {
    pub fn new(lock_merkle_proof: models::LockMerkleProofObject, pkh_signature: Vec<models::PkhSignatureObject>, hax: std::collections::HashMap<String, String>, tim: i64) -> WitnessObject {
        WitnessObject {
            lock_merkle_proof: Box::new(lock_merkle_proof),
            pkh_signature,
            hax,
            tim,
        }
    }
}

